Closes #97 and #98. Controllers tests
urfu-2016/team3 pull request #100
Opened 2017-04-24 12:16 UTC by Gebon

2017-04-24 12:16 UTC, Gebon commented
#98

2017-04-24 12:19 UTC, Gebon commented on package.json
> +    "jsmockito": "^1.0.5",
Remove

2017-05-14 06:49 UTC, Grehhov commented on tests/unit/controllers/photos.js
> +    it('.checkin successful', () => {
Наверно лучше тестировать не с абсолютно одинаковой широтой и долготой, а с погрешностью.

2017-05-14 06:49 UTC, Grehhov commented on tests/unit/controllers/quests.js
> +    it('.list', () => {
Может ещё проверить, что выводятся только опубликованные квесты и квесты самого пользователя?

2017-05-14 06:49 UTC, Grehhov commented on webpack.config.js
> +        error: './createQuest/pack.js',
Наверно здесь должно было быть './error/pack.js'. Но эта страница уже не нужна

2017-05-14 06:50 UTC, Grehhov requested changes
Комментарии выше

2017-05-14 08:27 UTC, Grehhov approved these changes

2017-05-14 08:40 UTC, merged