Closes #87. Add urls generator
urfu-2016/team3 pull request #102
Opened 2017-04-24 14:59 UTC by Gebon

2017-04-24 16:46 UTC, LeMarck requested changes

2017-04-24 16:46 UTC, LeMarck commented on utils/url-generator.js
> +const urljoin = require('url-join');
А вот [*эта*](https://nodejs.org/api/url.html#url_url_resolve_from_to) не делает тоже самое?

2017-04-24 16:46 UTC, LeMarck commented on utils/hbs-helpers.js
> +helpers.photoImageLink = urls.photos.image;
Может вынести хэлперы с линками в отдельный модуль?

2017-04-24 17:40 UTC, Gebon commented on utils/url-generator.js
> +const urljoin = require('url-join');
Нет, она немного по-другому работает. Можешь попробовать первый пример из доки выполнить с `url.resolve` и `urljoin`, должна быть видна разница. Я пока с телефона, поэтому не могу привести уже выполненный пример

2017-04-25 16:27 UTC, Grehhov requested changes

2017-04-25 16:27 UTC, Grehhov commented on utils/url-generator.js
> +        specific: id => urljoin(self.photos.root(), '{0}'.format([(id || ':id').toString()])),
Обязательно ли здесь и ниже нужен toString?

2017-04-25 17:56 UTC, Gebon commented on utils/url-generator.js
> +        specific: id => urljoin(self.photos.root(), '{0}'.format([(id || ':id').toString()])),
Да, конечно. Я же не просто так его вставил) Другое дело, что это повторяется, и я это вынесу. Спасибо, что напомнил

2017-04-25 19:48 UTC, Grehhov commented on utils/url-generator.js
> +        specific: id => urljoin(self.photos.root(), '{0}'.format([(id || ':id').toString()])),
Ок. Просто в других языках, где я встречал функцию format, достаточно было передать Object, без преобразования его в String.

2017-04-25 19:48 UTC, Grehhov approved these changes

2017-04-26 03:21 UTC, Gebon commented on utils/url-generator.js
> +        specific: id => urljoin(self.photos.root(), '{0}'.format([(id || ':id').toString()])),
В js нет встроенной функции форматирования. Я использовал string.format. Там какая-то магия, но я думаю, что проблема в JSON.decycled https://github.com/pillarsjs/String.format/blob/master/index.js

2017-04-26 17:56 UTC, IrinaSed approved these changes

2017-04-27 03:02 UTC, LeMarck requested changes

2017-04-27 03:02 UTC, LeMarck commented on utils/url-generator.js
> +        specific: id => urljoin(self.photos.root(), '{0}'.format([extractParameter(id)])),
```javascript
`${id || ':id'}/link`
```
Куда короче и не надо тянуть лишние либы

2017-04-27 03:23 UTC, LeMarck commented on utils/url-generator.js
> +module.exports = self = { // eslint-disable-line no-multi-assign
```javascript
const self = module.exports = { }
```

2017-04-27 05:48 UTC, Gebon commented on utils/url-generator.js
> +        specific: id => urljoin(self.photos.root(), '{0}'.format([extractParameter(id)])),
Это гениально. Не понимаю, почему сразу так не сделал)

2017-04-27 05:59 UTC, LeMarck requested changes

2017-04-27 05:59 UTC, LeMarck commented on utils/hbs-url-helpers.js
> +exports.photoImageLink = urls.photos.image;
А давай это не кидать в has, а подключать как middleware в котором все линки закинем в req.locales?
```javascript
req.locales.link = {
    photoImageLink =... 
   ... 
};
```

2017-04-27 06:03 UTC, Gebon commented on utils/hbs-url-helpers.js
> +exports.photoImageLink = urls.photos.image;
Зачем?

2017-04-27 08:07 UTC, LeMarck commented on utils/hbs-url-helpers.js
> +exports.photoImageLink = urls.photos.image;
Чтобы в шаблоне можно было вызвать
```handlebars
<img srs="{link.photoImageLink(id)}" alt="">
```

2017-04-27 08:21 UTC, Gebon commented on utils/hbs-url-helpers.js
> +exports.photoImageLink = urls.photos.image;
Сейчас вызывается `<img srs="{{ photoImageLink id }}" alt="">`. Что тут не так?

2017-04-27 08:22 UTC, LeMarck commented on utils/hbs-url-helpers.js
> +exports.photoImageLink = urls.photos.image;
Я просто предложил

2017-04-27 08:25 UTC, Gebon commented on utils/hbs-url-helpers.js
> +exports.photoImageLink = urls.photos.image;
Я думаю, что это не нужно

2017-04-27 08:26 UTC, LeMarck approved these changes

2017-04-27 08:58 UTC, Gebon commented on utils/hbs-url-helpers.js
> +exports.photoImageLink = urls.photos.image;
Хорошо, что ты начал эту дискуссию. Я только сейчас понял, что занимаюсь ерундой. Нужно просто в `res.locals` положить генератор URL-ов, чтобы не дублировать весь интерфейс в хелперах. То есть в hbs вместо `photoImageLink id` будет `urls.photo.image id`. Интерфейс будет меняться в одном месте. Плюс и фронтендер, и бэкендер будут использовать одинаковые интерфейсы, а значит разбираться в коде будет проще всем

2017-04-27 09:18 UTC, Gebon commented on utils/hbs-url-helpers.js
> +exports.photoImageLink = urls.photos.image;
Отбой, нельзя вызывать функции из `res.locals`. Обязательно нужно регистрировать helper

2017-04-27 09:19 UTC, merged