Closes #26, #27, #74 Добавил блок добавления новой фотографии и блок публикации
urfu-2016/team3 pull request #109
Opened 2017-05-01 19:03 UTC by Grehhov

2017-05-02 19:47 UTC, gallyamb requested changes

2017-05-02 19:47 UTC, Gebon commented on views/blocks/create_quest/index.hbs
> +            <div class="create-quest__captcha">{{{ captcha 'create-quest-form' 'create-quest__submit' }}}</div>
А зачем этот div всё-таки нужен?

2017-05-02 19:47 UTC, Gebon commented on views/blocks/quest_add_card/index.hbs
> +<form action="/photos" method="post" enctype="multipart/form-data" class="add-card-form">
URL нужно вынести в хелпер

2017-05-02 19:47 UTC, Gebon commented on views/blocks/quest_add_card/index.hbs
> +        {{> edit_text/index _id='longitude' _name='longitude' _label='explore' _type='text' _placeholder='Долгота'}}
Здесь и выше `type=number step=1e-9`

2017-05-02 19:47 UTC, Gebon commented on views/blocks/quest_add_card/index.js
> +        const inputFile = document.querySelector('.add-card-form__file-upload');
fileInputLabel

2017-05-02 19:47 UTC, Gebon commented on views/blocks/quest_add_card/index.js
> +    const fileImage = document.querySelector('.add-card-form__file');
fileInput or imageInput

2017-05-02 19:47 UTC, Gebon commented on views/blocks/quest_add_card/index.js
> +        const sectionForImage = document.querySelector('.add-card-form__file-section');
imageSection

2017-05-02 19:47 UTC, Gebon commented on views/blocks/quest_add_card/index.js
> +            .then(gps => {
({latitude, longitude}) => {}

2017-05-02 19:47 UTC, Gebon commented on views/blocks/quest_publish/index.hbs
> +    <input type="hidden" value="{{ quest._id }}" name="questId">
Зачем этот инпут?

2017-05-02 19:47 UTC, Gebon commented on views/blocks/textarea/index.styl
> +    &_max-height
&_height-limited

2017-05-02 19:47 UTC, Gebon commented on views/blocks/textarea/index.styl
> +    &_resize_none
&_height-fixed

2017-05-02 19:47 UTC, Gebon commented on scripts/geolocation.js
> +                    longitude: (lon[0] + (lon[1] / 60) + (lon[2] / 3600)) * (lonRef === 'W' ? -1 : 1)
А почему по умолчанию lonRef='W'? Можно было бы для удобства сделать 'E', и потом вынести эту часть в функцию

2017-05-08 14:20 UTC, Grehhov commented on views/blocks/create_quest/index.hbs
> +            <div class="create-quest__captcha">{{{ captcha 'create-quest-form' 'create-quest__submit' }}}</div>
Без него, когда капчи нет, кнопка создания квеста передвигается на место капчи

2017-05-08 14:21 UTC, Grehhov commented on views/blocks/quest_publish/index.hbs
> +    <input type="hidden" value="{{ quest._id }}" name="questId">
Я не помню как он здесь появился) Убрал его

2017-05-08 14:27 UTC, Grehhov commented on scripts/geolocation.js
> +                    longitude: (lon[0] + (lon[1] / 60) + (lon[2] / 3600)) * (lonRef === 'W' ? -1 : 1)
Этот код писал Женя, поэтому не могу сказать, почему lonRef сравнивается именно с 'W'. Но, кажется, вынесение части кода в функцию в данном случае не даёт никакого профита, так как количество строк кода не уменьшается, а даже увеличивается.

2017-05-09 13:48 UTC, Gebon commented on views/blocks/create_quest/index.hbs
> +            <div class="create-quest__captcha">{{{ captcha 'create-quest-form' 'create-quest__submit' }}}</div>
А как может так случиться, что капчи нет?

2017-05-09 13:50 UTC, Gebon commented on scripts/geolocation.js
> +                    longitude: (lon[0] + (lon[1] / 60) + (lon[2] / 3600)) * (lonRef === 'W' ? -1 : 1)
Так код выносится не только для уменьшения строк кода) Во-первых, убирается дублирование, во-вторых, повышается читаемость

2017-05-09 13:57 UTC, gallyamb requested changes

2017-05-09 13:57 UTC, Gebon commented on views/pages/createQuest/index.js
> +const addModifierForTextarea = () => {
Название слишком абстрактное. Я думаю, что `addHeightLimitedModifierToTextarea` лучше

2017-05-09 13:57 UTC, Gebon commented on views/blocks/edit_text/index.hbs
> +           step="{{ _step }}">
А если `_step` не передан, то получается этот тег будет просто так висеть.  Может обернуть в `{{#if _step}}...{{/if}}`?

2017-05-09 14:10 UTC, Gebon commented
Я потыкался на сайте, там при добавлении картинки без геоданных в консоль падает ошибка. Думаю, что это нужно как-то обработать

2017-05-13 19:04 UTC, Grehhov commented
@Gebon, добавил проверку полей и для остальных форм. Но пришлось убрать у капчи бинд на кнопку, и вызывать её (капчу) самостоятельно в зависимости от результатов проверки

2017-05-13 20:37 UTC, gallyamb requested changes
Не хватает `csrfHiddenInput` в формах.

2017-05-13 20:37 UTC, Gebon commented on scripts/validator-form-recaptcha.js
> +export const validatorFormReCaptcha = (buttonId, ids, recaptcha) => {
А зачем городить все это вместо использования атрибута `required` у `input`?  Есть, конечно, проблема для картинки, но это наверное проще будет обработать.

2017-05-13 20:37 UTC, Gebon commented on scripts/validator-form-recaptcha.js
> +export const validatorFormReCaptcha = (buttonId, ids, recaptcha) => {
Имя функции странное. Просто `validateForm`? Тут ведь нет привязки к капче. И без нее все сработает

2017-05-13 20:37 UTC, Gebon commented on utils/hbs-helpers.js
> -        `g-recaptcha" data-bind="${submitButtonId}" data-badge="inline" style="display: none" data`);
Наверное нужно еще и из сигнатуры функции это убрать?

2017-05-13 20:37 UTC, Gebon commented on views/blocks/create_quest/index.hbs
> +            <div class="create-quest__captcha">{{{ captcha 'create-quest-form' 'create-quest__submit' }}}</div>
Я не получил ответа на вопрос. Это же невозможно. Как капчи может не оказаться?

2017-05-13 20:37 UTC, Gebon commented on views/blocks/create_quest/index.js
> +    const fieldsRequired = ['name', 'description'];
`requiredFields`

2017-05-13 20:37 UTC, Gebon commented on scripts/geolocation.js
> +                    longitude: (lon[0] + (lon[1] / 60) + (lon[2] / 3600)) * (lonRef === 'W' ? -1 : 1)
Что тут с предыдущим обсуждением?

2017-05-13 22:11 UTC, Grehhov commented on scripts/validator-form-recaptcha.js
> +export const validatorFormReCaptcha = (buttonId, ids, recaptcha) => {
Функция изначально писалась для форм с капчей, поэтому было такое название. Городить пришлось, потому что в случае капчи, вызывается `submit()` у формы, но эта функция (в отличии от обычного нажатия на кнопку) не вызывает событие onsubmit, которое делает проверку полей `required`, а сразу отправляет данные на сервер.

2017-05-13 22:13 UTC, Grehhov commented on views/blocks/create_quest/index.hbs
> +            <div class="create-quest__captcha">{{{ captcha 'create-quest-form' 'create-quest__submit' }}}</div>
Забыл ответить. Когда ты мержил мой пр, капча была ещё не invisible. И иногда формочка "Я не робот" мне не показывалась (не знаю, по каким причинам). Тогда кнопка передвигалась на её место. Только сейчас я обратил внимание, что капча invisible, и то есть формы вообще нет, то есть можно не зависеть от неё. До этого я думал, что мне просто она всё ещё не показывается.

2017-05-14 06:13 UTC, gallyamb requested changes

2017-05-14 06:13 UTC, Gebon commented on scripts/geolocation.js
> +                (coordinate[0] + (coordinate[1] / 60) + (coordinate[2] / 3600));
Indentation

2017-05-14 12:17 UTC, gallyamb approved these changes

2017-05-14 12:32 UTC, merged