Closes #72 Текстовый редактор
urfu-2016/team3 pull request #114
Opened 2017-05-12 16:53 UTC by LeMarck

## Блок
* **publisher** - текстовый редактор с *emoji* :slightly_smiling_face: 

## Правки
* Стили **quest_checkin** импортируются внутри *index.js*

2017-05-12 18:55 UTC, Gebon commented
А почему этот ПР закрывает #79? Он же не про него вообще.
Еще нужно этот `publisher` (почему `publisher`, а не `editor` какой-нибудь? ) где-то вставить, чтобы можно было на него посмотреть в действии

2017-05-13 04:44 UTC, gallyamb requested changes
Зашёл с телефона. Блока для оставления комментария нет. Кажется, что-то пошло не так

2017-05-13 05:57 UTC, gallyamb requested changes
Я не знаю, почему кнопка подписки на квест на мобилах уехала вверх, но теперь из-за этого​ на странице квеста нельзя нажать на кнопку меню, где вход/регистрация.

Комментарии не работают.

На мобилах нельзя изменить стиль в одной строке

2017-05-13 05:57 UTC, Gebon commented on views/blocks/editor/index.js
> +    let isCall = false;
Не очень понятное имя. isCalled?

2017-05-13 05:57 UTC, Gebon commented on views/blocks/editor/index.js
> +    recovery() {
Имя не соотносится с телом. Это скорее getSaved

2017-05-13 05:57 UTC, Gebon commented on views/pages/quest/index.hbs
> +    </main>
Мне кажется, что main это квест и его фото, а комментарии это aside. Не для исправления, а для обсуждения это пишу

2017-05-13 05:57 UTC, Gebon commented on views/blocks/editor/index.js
> +            this._editor.addEventListener('input', throttle(this.save.bind(this), 10000));
Раз уж есть autosave, то можно и delay передать через опции

2017-05-13 05:57 UTC, Gebon commented on views/pages/quest/index.js
> +            if (response.status === 200) {
Эта штука не будет работать. Посмотри на реализацию метода на сервере

2017-05-13 06:04 UTC, Gebon commented
Я вообще не понимаю, зачем ты это все делаешь? Во-первых, эта задача не обсуждалась и не переводилась в ready, а в ready ещё есть задачи, которые нужно сделать. Во-вторых, задача, на которую ты ссылаешься - о markdown, а тут это вообще другое. Мне больше напоминает велосипед. Это, конечно, выглядит классно, но в проекте, я думаю, нужно использовать проверенные инструменты.

2017-05-13 06:06 UTC, gallyamb requested changes

2017-05-13 06:06 UTC, Gebon commented on views/pages/quest/index.hbs
> +                        <p>{{{text}}}</p>
Я бы не стал так доверять пользователям)

2017-05-13 06:09 UTC, LeMarck commented
Markdown был предложен как способ дать возможность пользователю писать красивый комментарий.
Одно из заданий было - emoji. Мне не сильно радует перспектива ревёрсить чужие редакторы ради внедрения в них emoji, к тому же они построены по аналогичному принципу работы.

2017-05-13 06:14 UTC, LeMarck commented on views/pages/quest/index.hbs
> +                        <p>{{{text}}}</p>
Вся прелесть *contenteditable* в том, что ты пишешь это
```html
<script>alert('hahaha!')</script>
```
а он преобразует в это
```html
&lt;script&gt;alert('hahaha!')&lt;/script&gt;
```

2017-05-13 06:17 UTC, LeMarck commented
Кнопка уехала вверх, так как **у квета не фотографий**, а значит нет главной фотки которая "делала отступ" от *header*

2017-05-13 06:31 UTC, Gebon commented on views/pages/quest/index.hbs
> +                        <p>{{{text}}}</p>
И ещё раз, никто не запрещает пользователю отправить запрос самому, без всех этих форм. О каком contenteditable тогда может идти речь?

2017-05-13 06:41 UTC, Gebon commented
Наверняка есть редакторы со встроенными emoji? Свои велосипеды всегда приходится поддерживать, а это не очень весело.
А маркдаун я предложил не столько из-за комментариев, а из-за описания квеста. Хотелось получить просто textarea, в нем написать markdown разметку, а на сервере это отрендерить. Ну если этот редактор можно приспособить ко всему, что захотим, то ок.

2017-05-13 06:47 UTC, LeMarck commented on views/pages/quest/index.hbs
> +                        <p>{{{text}}}</p>
Ну тут уже проблемы сервера, если он готов писать в базу всё что к нему приходит. Не думаешь?

2017-05-13 07:14 UTC, Gebon commented on views/pages/quest/index.hbs
> +                        <p>{{{text}}}</p>
Нет, не думаю) Эта штука тоже на сервере работает. Вот она и ответственна за escaping.

2017-05-14 06:15 UTC, gallyamb requested changes

2017-05-14 06:15 UTC, Gebon commented on views/blocks/editor/index.js
> +    getLocalStorage() {
Это название не подходит. `getFromLocalStorage`? Связанные названия соответственно

2017-05-14 06:15 UTC, Gebon commented on views/pages/quest/index.hbs
> +                        <p>{{{text}}}</p>
Еще раз

2017-05-14 12:54 UTC, gallyamb approved these changes

2017-05-14 12:59 UTC, merged