Closes #94 Сверстать страницу ошибки
urfu-2016/team3 pull request #115
Opened 2017-05-12 18:30 UTC by LeMarck

2017-05-12 18:59 UTC, gallyamb requested changes
Иногда у объекта `error` есть свойство `errors`, которое содержит список других ошибок. Типа агрегирующая ошибка. Нужно это тоже обрабатывать. Пример можно посмотреть [здесь](https://github.com/urfu-2016/team3/pull/100/files#diff-e8cc1ee8b491f814ddef53f0a5d0b255)

Ошибки не отображаются. Можно зайти в приложение и попробовать, например, обратиться к несуществующему квесту. Или открыть /about

2017-05-13 02:03 UTC, LeMarck commented
А зачем пользователю выдавать весь стэктрэйс? Ему достаточно знать, что ошибка 500/404/...

2017-05-13 04:34 UTC, Gebon commented
Кто-то говорил про стэктрейс? А вот код ошибки пользователю как раз таки не очень интересен. Он же ничего про это не знает. Ему важен текст ошибки.

2017-05-13 04:50 UTC, Gebon commented
Я не знаю, что я делаю не так, но


![screenshot_2017-05-13-09-49-00-157_com android chrome](https://cloud.githubusercontent.com/assets/5419623/26022539/94eb40b2-37c1-11e7-837b-91cf35ff5f06.png)

2017-05-13 05:26 UTC, Gebon commented
![screenshot_2017-05-13-10-25-46-070_com android chrome](https://cloud.githubusercontent.com/assets/5419623/26022755/91b20d72-37c6-11e7-95d6-6ced0a06f989.png)

2017-05-13 05:29 UTC, LeMarck commented
А можно не только скрины кидать, а ещё и описание того, что ты сделал?

2017-05-13 05:32 UTC, Gebon commented
Берешь и генерируешь любую ошибку. Верстка от этого не меняется же. Конкретно здесь попытался взять несуществующий квест

2017-05-13 09:44 UTC, gallyamb requested changes
Все еще нет обработки `error.errors`

2017-05-13 09:44 UTC, Gebon commented on routes/index.js
> +        const err = new Error('Not Found');
Пользователю не очень понятно, что именно не найдено. Может лучше 'There is nothing here. Maybe you mistyped something in URL?'. А 'Not found' слишком общо.

2017-05-13 09:44 UTC, Gebon commented on controllers/quests.js
> +            if (!('status' in err)) {
А в чем смысл такого финта?

2017-05-13 09:44 UTC, Gebon commented on views/pages/error/index.js
> +        item.innerText = code[index];
А почему это не shorthand?

2017-05-13 09:49 UTC, LeMarck commented on views/pages/error/index.js
> +        item.innerText = code[index];
Линтеру так больше нравится

2017-05-13 09:52 UTC, LeMarck commented on controllers/quests.js
> +            if (!('status' in err)) {
Чтобы не пробрасывать ошибки возникшие у **mongodb**. Например, твой пример (тавтология :slightly_smiling_face:) ошибки возник из-за того, что был передан не валидный **id** и результат прокинулся сразу в **catch**.

2017-05-13 09:53 UTC, LeMarck commented on routes/index.js
> +        const err = new Error('Not Found');
А может лучше использовать **русский язык**?

2017-05-13 10:03 UTC, Gebon commented on controllers/quests.js
> +            if (!('status' in err)) {
Как раз пользователю интересно, что возникло в монге. Там описывается понятная ошибка, так что пользователь сможет исправить ситуацию. А сейчас ему просто непонятный Not found придет. Этот catch ловит ошибки не только из-за того, что _id не нашелся. Да, это нужно обрабатывать и отдавать пользователю еще более читаемый текст, но пока лучше так

2017-05-13 10:06 UTC, Gebon commented on routes/index.js
> +        const err = new Error('Not Found');
Во-первых, никто не говорил, что аудитория сервиса ограничена русскоговорящими людьми. Английский, как более распространенный язык, вполне подходит для разработки. Если хочется по-хорошему, это все нужно выносить в языковые файлы и в коде использовать только фабрику, которая по настройкам текущего пользователя решит, какой язык ему отображать.
Но если ты хочешь чтобы было на русском, u r welcome)

2017-05-13 10:07 UTC, Gebon commented on routes/index.js
> +        const err = new Error('Not Found');
Главное не просто Not found

2017-05-13 10:10 UTC, LeMarck commented on routes/index.js
> +        const err = new Error('Not Found');
![image](https://cloud.githubusercontent.com/assets/11532954/26024605/3b2bad5a-37ee-11e7-89b3-824917a9fc81.png)

2017-05-13 10:19 UTC, LeMarck commented on controllers/quests.js
> +            if (!('status' in err)) {
Теперь я тебе перестаю понимать. В одном месте ты говоришь - *"А как же безопасность?"*. Подключаешь всякие "хреньки" для её обеспечивании. А тут *"пользователю интересно, что возникло в монге"*. WTF?
Какой у пользователя интерес в том, чтобы узнать, что введённый ими параметр поиска квеста в базе является не валидным или *"В таблице 'Quests' параметр '_id' был обработан не правильно"*.
*"пользователь сможет исправить ситуацию"*, начнёт дебажить из консоли? Можно ещё предлагать сделать **fork** и присылать на **PR** :slightly_smiling_face:

2017-05-13 10:20 UTC, Gebon commented on routes/index.js
> +        const err = new Error('Not Found');
И? Тут написано явно больше, чем 404 Not found. Тут явно указано, что нет такой **страницы**, а не чего-то еще. Предлагают сообщить, если пользователь считает, что страница таки должна быть тут.

2017-05-13 10:21 UTC, Gebon commented on routes/index.js
> +        const err = new Error('Not Found');
В нашем случае мы не можем пока принимать от пользователя запрос на отсутствующие страницы, так что просто говорим, что страницы нет, и может он URLом ошибся

2017-05-13 10:28 UTC, Gebon commented on controllers/quests.js
> +            if (!('status' in err)) {
Твое умение утрировать и доводить до абсурда, конечно, достойно похвалы.
Тем не менее, пользователь видит, что такой-то параметр неверный, значит он может его перепроверить. Судя по всему, ты читаешь только отрывками, так что напишу еще раз
>Да, это нужно обрабатывать и отдавать пользователю еще более читаемый текст, но пока лучше так

2017-05-14 12:36 UTC, Gebon commented on controllers/quests.js
> +            if (!('status' in err)) {
Нужно это перенести в `error.server` middleware

2017-05-14 13:01 UTC, gallyamb approved these changes

2017-05-14 13:18 UTC, merged