Closes #112 and #113 Обновление галереи
urfu-2016/team3 pull request #122
Opened 2017-05-15 06:03 UTC by LeMarck

## Utils
* **html-sanitizer.js** - экранирует html-теги

## Update
* **touch-emitter.js** - улучшено поведение на touch-события
* **editor** - добавлена поддержка *placeholder*

2017-05-15 09:46 UTC, gallyamb requested changes

2017-05-15 09:46 UTC, Gebon commented on controllers/quests.js
> +const htmlSanitizer = require('../utils/html-sanitizer');
Это должен быть либо `sanitizeHtml`, либо у `htmlSanitizer` должен быть метод `sanitize`. А то как-то странно получается во время использования

2017-05-15 09:46 UTC, Gebon commented on utils/html-sanitizer.js
> +    'form', 'video', 'img', 'audio', 'style'
Из первого, что еще приходит на ум: iframe. Мне кажется, что стоит наоборот, сделать список разрешенных тегов. Все остальные по-умолчанию запрещены

2017-05-16 03:21 UTC, gallyamb requested changes

2017-05-16 03:21 UTC, Gebon commented on utils/hbs-helpers.js
> +        const newValue = items.shift();
Воу воу, палехче) Давай использовать `pop/for`. Это же капец какая дорогая операция

2017-05-16 03:21 UTC, Gebon commented on views/pages/main/index.hbs
> +                     '{"icon":"?", "link": ":about"}' '{"icon":"exit_to_app", "link": ":logout"}'}}
Я считаю, что это не круто, когда пользователю, чтобы зайти в профиль/выйти, нужно идти на главную страницу, там тыкать в меню и только потом делать действие

2017-05-16 03:21 UTC, Gebon commented on utils/html-sanitizer.js
> +].map(item => new RegExp(`<(/?${item}.*?)>`, 'gi'));
Что в итоге с белым списком?

2017-05-16 03:28 UTC, LeMarck commented on views/pages/main/index.hbs
> +                     '{"icon":"?", "link": ":about"}' '{"icon":"exit_to_app", "link": ":logout"}'}}
Надо добавить menu на все страницы

2017-05-16 03:29 UTC, LeMarck commented on utils/hbs-helpers.js
> +        const newValue = items.shift();
Хорошо

2017-05-16 03:29 UTC, LeMarck commented on utils/html-sanitizer.js
> +].map(item => new RegExp(`<(/?${item}.*?)>`, 'gi'));
Не могу придумать регулярку под белый список

2017-05-16 04:10 UTC, Gebon commented on utils/html-sanitizer.js
> +].map(item => new RegExp(`<(/?${item}.*?)>`, 'gi'));
Именно поэтому я говорю про то, что велосипеды не нужны. Есть уже проверенные библиотеки. https://github.com/punkave/sanitize-html

2017-05-16 04:12 UTC, Gebon commented on views/pages/main/index.hbs
> +                     '{"icon":"?", "link": ":about"}' '{"icon":"exit_to_app", "link": ":logout"}'}}
Ок, тогда сделай в этой же задаче ещё и layout,  а то дублирования чот много уже

2017-05-16 04:47 UTC, Gebon commented
На мобилах при просмотре увеличенной картинки все равно можно свайпнуть и переключить картинку

2017-05-16 04:48 UTC, Gebon commented
`editor` нужно как-то визуально выделять, потому что непонятно, что он вообще есть. Особенно на странице создания квеста сложно определить его геометрию

2017-05-16 04:50 UTC, Gebon commented
Для emoji нужно подключить какой-нибудь шрифт, потому что на некоторых браузерах (Ubuntu/Chrome) отображается так:
![2017-05-16 09-49-35](https://cloud.githubusercontent.com/assets/5419623/26090239/fbed2782-3a1c-11e7-92f1-24e3d146bd3d.png)
В крайнем случае хотя бы поменять шрифт на белый у `.editor button`

2017-05-17 07:01 UTC, Gebon commented
* Если кликать в пустое поле ввода, в консоли появляются ошибки
 * Emoji можно открыть и посмотреть только один раз. Больше не открываются.
 * Подсветка кнопок иногда не работает. Т.е. кнопку нажали, но она не подсвечивается. Если нажать на поле ввода еще раз, то кнопка начинает светиться

2017-05-17 12:16 UTC, gallyamb requested changes

2017-05-17 12:16 UTC, Gebon commented on auth/vk-strategy.js
> +    avatar: profile.photos[0].value
А если у пользователя вообще нет фотографий, подставится дефолтный как в твиттере? У меня прост нет аккаунта без фоток

2017-05-17 12:16 UTC, Gebon commented on utils/hbs-helpers.js
> +});
Мне кажется, что лучше эту работу сделать на клиенте простым new Date(date).toLocaleString(), чтобы это все зависело от временной зоны и языковых настроек клиента. Думаю, что незачем прибивать гвоздями на сервере.

2017-05-17 12:19 UTC, Gebon commented on views/blocks/editor/index.js
>              }
Нужно оставить просто `this._emojitools.dataset.show = 'false';` без `if`. Нет же никакой разницы. Если `true` -> `false, если `false` -> `false`

2017-05-17 12:20 UTC, Gebon commented
Еще остался шрифт для emoji

2017-05-17 12:22 UTC, LeMarck commented on utils/hbs-helpers.js
> +});
Хорошо

2017-05-17 12:23 UTC, LeMarck commented on views/blocks/editor/index.js
>              }
Хорошо

2017-05-17 16:34 UTC, gallyamb approved these changes

2017-05-17 17:42 UTC, merged