Closes #84 Редактирование/удаление квеста
urfu-2016/team3 pull request #123
Opened 2017-05-17 14:50 UTC by Grehhov

2017-05-17 16:17 UTC, Gebon commented on controllers/quests.js
> +        .then(() => Quest.deleteOne({_id: new mongodb.ObjectID(req.params.id)}))
Я думаю, что не нужно обращаться к `mongodb`, т.к. мы используем `mongoose`. Вполне возможно, что `mongoose` решит использовать реализацию отличную от реализации в `mongodb`. А вообще, тут можно `Quest.findByIdAndRemove(req.params.id)`.

2017-05-17 16:24 UTC, Gebon commented on views/blocks/quest_description/index.hbs
> +            {{#ifOr _user.isAuthor _user.isAdmin}}
По-моему, нужно просто в контроллере проставить свойство `quest.isAccessibleToCurrentUser = quest.isAccessibleToUser(req.user);`. Тогда и `ifOr` не понадобиться

2017-05-17 20:50 UTC, gallyamb requested changes

2017-05-17 20:50 UTC, Gebon commented on controllers/quests.js
> +                throw err;
В мастере уже есть `createError`

2017-05-17 20:50 UTC, Gebon commented on controllers/quests.js
> +                throw err;
И тут

2017-05-17 20:50 UTC, Gebon commented on tests/unit/controllers/quests.js
> +        const mockSave = sinon.stub(questMock, 'save').callsFake(() => {
`sinon -> sandbox`

2017-05-17 20:50 UTC, Gebon commented on tests/unit/controllers/quests.js
> +            questMock.name = 'Quest 2';
Очень странный тест получается. Ты проверяешь, что твоя мока действительно работает. А тебе нужно проверить, что твой контроллер работает

2017-05-17 20:50 UTC, Gebon commented on views/pages/quest/index.js
> +    const sendQueryEdit = (fieldName, value) => {
`sendEditQuery`

2017-05-17 20:53 UTC, Gebon commented
Я не понимаю, почему вместо `editor` используется `textarea`

2017-05-18 03:10 UTC, LeMarck requested changes
При удалении квеста не редиректит на главную

2017-05-18 03:10 UTC, LeMarck commented on views/blocks/description/index.styl
> +    align-self center
`align-self flex-start` чтобы не прыгала

2017-05-18 06:27 UTC, Gebon commented
Меня редиректит

2017-05-18 06:28 UTC, Gebon commented on views/blocks/description/index.styl
> +    align-self center
+

2017-05-18 08:18 UTC, gallyamb approved these changes

2017-05-18 12:26 UTC, LeMarck approved these changes

2017-05-18 12:41 UTC, merged