Лайки и подписка на квест
urfu-2016/team3 pull request #128
Opened 2017-05-18 02:39 UTC by Grehhov

2017-05-18 03:03 UTC, LeMarck requested changes

2017-05-18 03:03 UTC, LeMarck commented on views/blocks/quest_description/index.hbs
> +                    {{#unless user.isLikedToCurrentQuest}}
Давай кнопку лайка показывать, только после взятия квеста, либо навесь событие на иконку лайка в description
А то два float'а выглядят ужасно

2017-05-18 04:09 UTC, Gebon commented on views/blocks/quest_description/index.hbs
> +                    {{#unless user.isLikedToCurrentQuest}}
isLikedByCurrentUser

2017-05-18 04:17 UTC, gallyamb requested changes
Раз уж теперь есть поле passing quest, нужно изменить логику в checkin

2017-05-18 04:17 UTC, Gebon commented on models/user/configure-user-schema.js
> +    schema.methods.isQuestPasses = function (quest) {
isQuestPassing

2017-05-18 04:17 UTC, Gebon commented on models/user/user-schema-object.js
> +    passesQuests: [{type: ObjectId, ref: 'Quest', index: true}],
passingQuests

2017-05-18 04:17 UTC, Gebon commented on controllers/quests.js
> +                req.user.isLikedToCurrentQuest = req.user.isQuestLiked(quest);
isLikedCurrentQuest

2017-05-18 04:17 UTC, Gebon commented on controllers/quests.js
> +                req.user.isPassToCurrentQuest = req.user.isQuestPassed(quest) || req.user.isQuestPasses(quest);
isPassingCurrentQuest

2017-05-18 07:04 UTC, Gebon commented on controllers/quests.js
> +                throw createError(`You already pass or passed quest with is ${req.params.id}`, HttpStatus.FORBIDDEN);
You already pass**ing** or passed **the** quest ...

2017-05-18 11:10 UTC, gallyamb approved these changes

2017-05-21 11:44 UTC, LeMarck approved these changes

2017-05-21 13:00 UTC, merged