#6 сверстали quest preview block
urfu-2016/team3 pull request #17
Opened 2017-03-12 13:10 UTC by IrinaSed

2017-03-12 15:27 UTC, gallyamb requested changes

2017-03-12 15:27 UTC, Gebon commented on views/pages/main/index.styl
> +<<<<<<< ce25f968efc0006433a1fabfe616195c1fbf4696
Кажется конфликт все таки не разрешился) Ну и комментарий к коммиту должен быть содержательным

2017-03-13 14:05 UTC, gallyamb requested changes

2017-03-13 14:05 UTC, Gebon commented on views/pages/main/index.styl
> +@import "../../blocks/preview/index.styl"npm
`npm` здесь кажется лишний

2017-03-13 14:05 UTC, Gebon commented on views/pages/main/index.styl
> +@import "../../blocks/preview/index.styl"npm
Нужно сделать один коммит

2017-03-13 14:07 UTC, Gebon commented on views/pages/main/index.styl
> +@import "../../blocks/preview/index.styl"npm
Содержательный комментарий requested. Предлагаю `Closes #6. Сверстали черновую версию блока quest_preview`

2017-03-13 14:07 UTC, gallyamb commented
Нужно сделать один коммит.

Содержательный комментарий requested. Предлагаю `Closes #6. Сверстали черновую версию блока quest_preview`

2017-03-13 14:09 UTC, Gebon commented
Как вариант, можно сделать так:
```sh
git reset --soft HEAD~4
git add # нужные файлы
git commit -m "Closes #6. Сверстали черновую версию блока quest_preview"
git push -f origin quest_preview
```

2017-03-13 14:58 UTC, gallyamb approved these changes

2017-03-14 04:36 UTC, LeMarck approved these changes

2017-03-14 04:37 UTC, merged