#32 Improve npm scripts
urfu-2016/team3 pull request #33
Opened 2017-03-12 16:21 UTC by Gebon

Сделал возможность запустить webpack-watch и сервер одной командой

2017-03-12 16:21 UTC, Gebon commented
@Gebon, thanks for your PR! By analyzing the history of the files in this pull request, we identified @LeMarck to be a potential reviewer.

2017-03-12 16:34 UTC, Gebon commented
В чем профит: не нужно запускать два отдельных процесса для сервера и webpack-watch

2017-03-13 08:25 UTC, IrinaSed approved these changes

2017-03-13 08:57 UTC, svl96 approved these changes

2017-03-13 09:09 UTC, LeMarck requested changes

2017-03-13 09:09 UTC, LeMarck commented on package.json
> +    "start": "npm-run-all --parallel start:*",
Верни названия как они были, а это назови `npm run start:dev`

2017-03-13 09:20 UTC, MentionBot-Team3 commented on package.json
> +    "start": "npm-run-all --parallel start:*",
А какая причина?

2017-03-13 09:20 UTC, Gebon commented on package.json
> +    "start": "npm-run-all --parallel start:*",
А какая причина?

2017-03-13 09:24 UTC, Gebon commented on package.json
> +    "start": "npm-run-all --parallel start:*",
Насколько я помню, основная претензия к предыдущей версии была в том, что если запустить и сервер, и watcher, то это сделает неудобным серверную разработку. Теперь все удобно.

2017-03-13 09:35 UTC, LeMarck commented on package.json
> +    "start": "npm-run-all --parallel start:*",
Из семантических причин
`npm install` - *Установка зависимостей*
`npm run build` - *Сборщик*
`npm start` - *Запуск приложения*

Тогда как команда `npm run start:dev` мне точно укажет на то, что сейчас запущенное приложение в dev mode

2017-03-13 10:04 UTC, Gebon commented
Summon @LeMarck

2017-03-13 10:16 UTC, LeMarck approved these changes

2017-03-13 10:18 UTC, merged