Closes #22. Add registration page.
urfu-2016/team3 pull request #40
Opened 2017-03-17 16:12 UTC by Gebon

2017-03-19 16:14 UTC, LeMarck requested changes

2017-03-19 16:14 UTC, LeMarck commented on views/blocks/registration-form/index.styl
> +.registration-form__input
`&__input`

2017-03-19 16:14 UTC, LeMarck commented on views/blocks/registration-form/index.styl
> +.registration-form__submit
`&__submit`

2017-03-19 16:14 UTC, LeMarck commented on views/blocks/registration-form/index.hbs
> +<form class="registration-form" action="/users/register" method="post">
Есть предложение сделать `action={{ __url }}`
И в использовать такую конструкцию `{{> registration-form/index __url='/users/register' }}`
Тогда эту форму можно будет использовать несколько раз, для разных url

2017-03-19 19:04 UTC, IrinaSed commented
можешь сделать блок по середины странице(по высоте)
![image](https://cloud.githubusercontent.com/assets/20294935/24083791/bdac2f3a-0cff-11e7-9c0e-85f60c14f7a3.png)

2017-03-19 19:15 UTC, IrinaSed requested changes
)

2017-03-20 19:58 UTC, Gebon commented
@JackSparrowBot @IrinaSed done

2017-03-21 08:30 UTC, IrinaSed commented
так было задумано??? Что за поля пустые?
![image](https://cloud.githubusercontent.com/assets/20294935/24138554/72ee9d0c-0e3a-11e7-929d-33fd90394e68.png)

2017-03-21 08:33 UTC, Gebon commented
@IrinaSed было бы классно еще и вывод консоли показать. Задумано было слегка получше)

2017-03-21 08:33 UTC, Gebon commented
@IrinaSed надеюсь, ты не забыла сделать `npm i`

2017-03-21 08:49 UTC, IrinaSed commented
всё круто

2017-03-21 08:59 UTC, IrinaSed approved these changes

2017-03-22 11:54 UTC, closed without merging