Closes #24. Сверстала страницу checkin
urfu-2016/team3 pull request #41
Opened 2017-03-19 15:22 UTC by IrinaSed

2017-03-19 15:33 UTC, Gebon commented on controllers/checkin.js
> + * Created by irina on 16.03.17.
Я думаю, что этот комментарий бесполезен. Может его лучше убрать?

2017-03-19 15:47 UTC, gallyamb requested changes

2017-03-19 15:47 UTC, Gebon commented on views/blocks/submit/index.hbs
> +<form method="post" class="submit-form">
Какой-то абстрактный `submit-form`. Думаю было бы лучше `checkin-form`

2017-03-19 15:47 UTC, Gebon commented on views/blocks/submit/index.hbs
> +        <div class="submit-form__coordinates_div">
Я бы назвал это `checkin-form__input`

2017-03-19 15:47 UTC, Gebon commented on views/blocks/submit/index.hbs
> +            <input id="longitude" type="text">
Нужны атрибуты `name` в обоих инпутах

2017-03-19 15:47 UTC, Gebon commented on views/blocks/submit/index.styl
> +  border: 2px solid-grey
Здесь, наверное, подразумевалось `2px solid grey`. Еще лучше заменить `grey` на какое-нибудь hex представление.

2017-03-19 15:47 UTC, Gebon commented on views/blocks/submit/index.styl
> +    margin-top 2%
Двоеточия, точки с запятыми - неконсистентно. Давай в одном стиле. У нас stylint чот не работает, кажется

2017-03-19 15:47 UTC, Gebon commented on views/blocks/submit/index.styl
> +
Много переносов строк

2017-03-19 15:47 UTC, Gebon commented on views/blocks/submit/index.styl
> +    margin-bottom: 2%
Точно нужен `margin` в процентах?

2017-03-19 15:47 UTC, Gebon commented on views/pages/checkin/index.hbs
> +    <section class="submit">
Еще раз продублирую про название: `checkin`?

2017-03-19 15:47 UTC, Gebon commented on views/pages/checkin/index.styl
> +  background: #F5FD72
Строчные буквы нужны

2017-03-19 16:21 UTC, LeMarck requested changes

2017-03-19 16:21 UTC, LeMarck commented on views/blocks/preview/index.styl
> +.preview__description
Измени структуру
```styl
.preview
  ...
  &__description
    ...
  &:hover
    ...
    &__description
      ...
```

2017-03-19 16:21 UTC, LeMarck commented on views/blocks/submit/index.hbs
> +        <input class="submit-form__coordinates_input" type="submit">
```html
<button>Отправить</button>
```

2017-03-19 16:51 UTC, Gebon commented on views/blocks/preview/index.styl
> +.preview__description
Нужно `preview:hover preview__description`
Т.е.
```stylus
.preview
  ...
  &__description
    ...
  &:hover
    ...
  &:hover &__description
    ...
```
`&` всегда указывает на селктор непосредственного родителя, так ведь?

2017-03-19 17:40 UTC, LeMarck commented on views/blocks/preview/index.styl
> +.preview__description
@Gebon, спасибо за замечание

2017-03-19 19:04 UTC, LeMarck requested changes

2017-03-19 19:04 UTC, LeMarck commented on views/blocks/checkin_form/index.styl
> +      & input
Можно просто писать `input`

2017-03-19 19:04 UTC, LeMarck commented on views/blocks/checkin_form/index.styl
> +      & input::-webkit-input-placeholder
А тут сделать отступ и написать `&::-webkit-input-placeholder`

2017-03-20 04:31 UTC, gallyamb requested changes
Два коммита. Нужно оставить один

2017-03-20 04:31 UTC, Gebon commented on views/blocks/checkin_form/index.hbs
> +        <div class="checkin-form__coordinates_input">
`checkin-form__input `. Сейчас это невалидный бэм

2017-03-20 04:31 UTC, Gebon commented on views/blocks/checkin_form/index.hbs
> +        <img src="some-photo.jpg" class="checkin-form__photo_big-img">
`checkin-form__image `. Невалидный бэм

2017-03-20 04:31 UTC, Gebon commented on views/blocks/checkin_form/index.styl
> +      & input:-moz-placeholder
А нет универсального селектора? Типа `input: placeholder `

2017-03-20 04:31 UTC, Gebon commented on views/blocks/checkin_form/index.hbs
> +        <button class="checkin-form__coordinates_button" type="submit">Отправить</button>
Невалидный бэм

2017-03-20 08:40 UTC, IrinaSed commented on views/blocks/checkin_form/index.styl
> +      & input:-moz-placeholder
я не нашла

2017-03-20 08:54 UTC, Gebon commented on views/blocks/checkin_form/index.styl
> +      & input:-moz-placeholder
[Тут](http://caniuse.com/#search=%3A%3Ap) говорят, что есть. Думаю, что лучше добавить стандартную версию.
Еще можно/нужно вместо
```stylus
x
  color: #000
y
  color: #000
```
писать
```stylus
x,
y
  color: #000
```

2017-03-20 08:55 UTC, Gebon commented on views/blocks/checkin_form/index.styl
> +      & input:-moz-placeholder
В БЭМ вроде нельзя по селектору тега обращаться. Могу ошибаться

2017-03-20 17:52 UTC, IrinaSed commented on views/blocks/checkin_form/index.styl
> +      & input:-moz-placeholder
Это не работает ::p, наверное потому что там значок -wd красненький;
пишу раздельно селекторы
x:
  color
y:
  color
потому что иначе тоже не работает

2017-03-20 18:02 UTC, IrinaSed commented on views/blocks/checkin_form/index.hbs
> +        <img src="some-photo.jpg" class="checkin-form__photo_big-img">
Тип забиваем на стиль stylus,
и используем бэм
Бэм приоритетнее?

2017-03-20 18:02 UTC, IrinaSed commented on views/blocks/checkin_form/index.hbs
> +        <img src="some-photo.jpg" class="checkin-form__photo_big-img">
http://stylus-lang.com/docs/selectors.html

2017-03-21 02:50 UTC, Gebon commented on views/blocks/checkin_form/index.hbs
> +        <img src="some-photo.jpg" class="checkin-form__photo_big-img">
У stylus по определению нет стиля в именовании селекторов. Это же просто препроцессор css

2017-03-21 02:58 UTC, Gebon commented on views/blocks/checkin_form/index.styl
> +      & input:-moz-placeholder
`Это не работает ::p, наверное потому что там значок -wd красненький` - раскрой, пожалуйста, мысль. Я не понял. 

`потому что иначе тоже не работает` - а в чем это выражается? Только что в онлайн трансляторе попробовал именно с этими селекторами — все работает

2017-03-21 08:27 UTC, IrinaSed commented
при мерже сделаю один коммит

2017-03-21 11:01 UTC, gallyamb requested changes
В styl файлах где-то есть `:`, а где-то нет

2017-03-21 11:01 UTC, Gebon commented on views/blocks/checkin_form/index.styl
> +  &__coordinates-input
```stylus
.checkin-form
  ...
  &__coordinates
    ...
    &-input
      ...
    &-button
      ...
```

2017-03-21 11:01 UTC, Gebon commented on views/blocks/checkin_form/index.styl
> +  &__div-image
```stylus
.checkin-form
  ...
  &__div
    ...
    &-image
      ...
```
.checkin-form__**div** - не очень семантичное название элемента. Есть возможность улучшить название?

2017-03-21 11:01 UTC, Gebon commented on views/blocks/checkin_form/index.styl
> +    input
Такой вложенности и селектора тега в БЭМ быть не должно

2017-03-21 11:01 UTC, Gebon commented on views/blocks/checkin_form/index.styl
> +      &::-webkit-input-placeholder
Про это говорил в прошлом ревью. Там добавил еще коммент. Ответь, пожалуйста, на тот коммент здесь.

2017-03-21 18:23 UTC, IrinaSed commented on views/blocks/checkin_form/index.styl
> +      &::-webkit-input-placeholder
Вот не работает:
![1](https://cloud.githubusercontent.com/assets/20294935/24163719/31d1f53c-0e8d-11e7-87a7-e5e84cf8a5b4.png)
Вот работает:
![1](https://cloud.githubusercontent.com/assets/20294935/24163806/6c5874ba-0e8d-11e7-8473-7d4fc558d7af.png)

2017-03-21 18:26 UTC, IrinaSed commented on views/blocks/checkin_form/index.styl
> +      &::-webkit-input-placeholder
Вот так нельзя:
x,
y {css}
в данном случае, потому что просто не работает, если их написать через запятую

2017-03-21 18:29 UTC, IrinaSed commented on views/blocks/checkin_form/index.styl
> +      &::-webkit-input-placeholder
-wd на сайте(там есть иконка) на can i use, вот, и она там красная, я подозреваю что еще просто не добавили

2017-04-05 15:03 UTC, closed without merging