#38. Setup infrastructure. Add few more npm scripts
urfu-2016/team3 pull request #45
Opened 2017-03-21 09:40 UTC by Gebon

* Для интеграции с Heroku добавил middleware для прокидывания адреса Surge.
* Добавил npm скрипты для очистки окружения (node_modules, public)
* Добавил скрипт деплоя в surge

Пока не ставлю `Closes #38`, потому что непонятно, нужны ли будут еще работы, пока не проверим конфигурацию

2017-03-21 09:56 UTC, LeMarck requested changes

2017-03-21 09:56 UTC, LeMarck commented on package.json
>      "start": "cross-env NODE_ENV=production node .",
Убери `NODE_ENV`

2017-03-21 09:56 UTC, LeMarck commented on index.js
> +    app.use(express.static(publicDir));
Вынеси из if, middleware его потом переопределит, если надо

2017-03-21 09:56 UTC, LeMarck commented on index.js
> -app.use(logger('dev'));
Оставь как было, чтобы лог отображался при любом окружении

2017-03-21 10:02 UTC, Gebon commented on index.js
> -app.use(logger('dev'));
Лог и так отображается при любом окружении. В продакшене используется `logger('short')`

2017-03-21 10:02 UTC, Gebon commented on index.js
> +    app.use(express.static(publicDir));
Кто его переопределит?

2017-03-21 10:04 UTC, Gebon commented on package.json
>      "start": "cross-env NODE_ENV=production node .",
Зачем? Хотим запускать в продакшен окружении. На это опирается какой-то код. Если ты про то, что, скажем, Heroku сам выставляет такую же переменную, то это не страшно. Так мы в любом окружении можем быть уверены в значении этой переменной

2017-03-21 10:06 UTC, Gebon commented on index.js
> +    app.use(express.static(publicDir));
Раскрою мысль. Эта штука нужно **только** в девелопменте. Потому что в остальных случаях используется Surge, и наше приложение вообще не знает ничего о статике

2017-03-21 10:25 UTC, Gebon commented on index.js
> -app.use(logger('dev'));
Дошло. Использовать dev как fallback. Хорошая идея

2017-03-21 18:03 UTC, IrinaSed approved these changes

2017-03-21 18:07 UTC, Gebon commented on middlewares/common-data.js
> +        description: 'Awesome photo quests'
@LeMarck мне кажется, что это стоит оставить как fallback для тех страниц, где description по каким-то причинам отсутствует

2017-03-21 18:25 UTC, LeMarck requested changes

2017-03-21 18:25 UTC, LeMarck commented on package.json
> +    "start": "node .",
```json
"start": "cross-env NODE_ENV=locale node ."
```

2017-03-21 18:25 UTC, LeMarck commented on package.json
> +    "production": "cross-env NODE_ENV=production node .",
`"production"` -> `"deploy:heroku"`

2017-03-21 18:25 UTC, LeMarck commented on package.json
> +    "deploy:surge": "surge --project ./public --domain team3.surge.sh"
```json
"deploy:surge": "npm run build && surge --project ./public --domain team3.surge.sh"
```

2017-03-21 18:33 UTC, Gebon commented on package.json
> +    "start": "node .",
В чем смысл?

2017-03-21 18:34 UTC, Gebon commented on package.json
> +    "start": "node .",
Думаю, что лучше оставить так. Потому что эта переменная может быть задана извне. Иначе не вижу смысла в переделке `"start": "cross-env NODE_ENV=production node ."`

2017-03-21 18:35 UTC, Gebon commented on package.json
> +    "start": "node .",
Есть два вида: production и dev. На остальное есть default в switch/case

2017-03-21 18:36 UTC, LeMarck commented on package.json
> +    "start": "node .",
Это просто предложение
* `dev` - для разработки
* `production` - для прода
* `locale` - для локального развёртывания

2017-03-21 18:36 UTC, Gebon commented on package.json
> +    "production": "cross-env NODE_ENV=production node .",
Ну это не деплой. Это просто запуск сервера. Деплой - это выкладка файлов на удаленный сервер (Surge)

2017-03-21 18:48 UTC, LeMarck commented on index.js
> +    default:
Тут сугубо придирка, которая на *review* ни как не повлияет, но этот **switch** выглядит ужасно)))

Как по мне, `app.use(logger('dev'));` **вынести из switch** и пусть пишутся все логи.
`hbsutils.registerWatchedPartials(partialsDir);` можно совсем **убрать**, так как у нас есть **nodemon**.
А **switch заменить** на 
```js
if (process.env.NODE_ENV in ['dev', 'locale']) app.use(express.static(publicDir));
```

2017-03-21 18:58 UTC, LeMarck commented on package.json
> +    "production": "cross-env NODE_ENV=production node .",
Вообще не вижу смысла в этом скрипте, так как *NODE_ENV=production* по умолчанию стоит у Heroku и всё что надо, чтобы запуститься - написать в **Procfile**
```
web: node app/index.js
```

2017-03-21 19:07 UTC, Gebon commented on package.json
> +    "start": "node .",
Я подумал и не понял профита от `local`. Решил оставить `npm start === production mode`, `npm run dev:server === development mode`

2017-03-21 19:24 UTC, Gebon commented
@LeMarck

2017-03-22 01:22 UTC, LeMarck approved these changes

2017-03-22 01:31 UTC, merged

2017-03-22 02:55 UTC, Gebon commented
#39