Close #3 Главная страница
urfu-2016/team3 pull request #52
Opened 2017-03-22 05:20 UTC by LeMarck

Блоки:
* *header*
* *questPreview*
* *searchForm*
* *filterPanel*
* *floatingButton*

Страницы - **main**

Добавил в *Handlerbars* helper'ы:
* `{{#array "['one', 'two']" }}{{/array}}` - создаёт массив
* `{{#or 'value' 'default'}}{{/or}}` - эквивалент `value || default` для *Handlerbars*

2017-03-22 05:52 UTC, gallyamb requested changes

2017-03-22 05:52 UTC, Gebon commented on views/blocks/filterPanel/index.hbs
> +    {{#each __filds}}
fields

2017-03-22 05:52 UTC, Gebon commented on index.js
> +if (process.env.NODE_ENV !== 'production') {
А что плохого в разделении логгеров?

2017-03-22 05:52 UTC, Gebon commented on package.json
> -    "start": "cross-env NODE_ENV=production node .",
Верни. Нужно, чтобы приложение запускалось всегда в одном из двух режимов production/dev. Зачем поддерживать другие?

2017-03-22 05:52 UTC, Gebon commented on views/blocks/filterPanel/index.styl
> +  color $color
Думаю, стоит обозвать переменную более понятным именем. Например textColor

2017-03-22 05:52 UTC, Gebon commented on views/blocks/questPreview/index.hbs
> +            <img class="quest-preview__images-img" src="http://oboi.pw/uploads/new/big/oboik.ru_23367.jpg" alt="">
big/small похожи на модификатор, но img не похож. Может оставить просто image?

2017-03-22 05:59 UTC, LeMarck commented on views/blocks/filterPanel/index.hbs
> +    {{#each __filds}}
Двойное подчёркивание - экранирование *переменных блоков* от *переменных передаваемых* в шаблон

2017-03-22 06:04 UTC, LeMarck commented on package.json
> -    "start": "cross-env NODE_ENV=production node .",
Зачем использовать *production* конфигурацию при локальном запуске?

2017-03-22 06:05 UTC, Gebon commented on views/blocks/filterPanel/index.hbs
> +    {{#each __filds}}
Ты неправильно понял. Я про само слово. Ошибка там

2017-03-22 06:06 UTC, Gebon commented on package.json
> -    "start": "cross-env NODE_ENV=production node .",
Есть dev. npm run dev:server

2017-03-22 06:19 UTC, LeMarck commented on package.json
> -    "start": "cross-env NODE_ENV=production node .",
А зачем мне *dev* версия если я просто хочу посмотреть проект?

2017-03-22 06:20 UTC, LeMarck commented on views/blocks/filterPanel/index.hbs
> +    {{#each __filds}}
Уже поправил, сразу не заметил.

2017-03-22 06:24 UTC, Gebon commented on package.json
> -    "start": "cross-env NODE_ENV=production node .",
А какая разница между dev и просто посмотреть? И если уж так хочется запустить просто node ., то никто этого и не запрещает.

2017-03-22 07:39 UTC, gallyamb requested changes
А давай делать так: не нужно каждый раз схлапывать изменения в один коммит. Вот я посмотрел предыдущую версию, там были какие-то обсуждения. Если схлопнуть все и опять сделать один коммит, мне придется еще раз полностью все изменения просмотреть. А если делать коммиты-фиксы, то сразу работы меньше. А вот в конце, когда все пришли к согласию, делать один коммит и мерджить

2017-03-22 07:39 UTC, Gebon commented on package.json
> -    "dev:server": "cross-env NODE_ENV=dev nodemon .",
Здесь в чем проблема?

2017-03-22 07:39 UTC, Gebon commented on package.json
> +    "deploy": "npm-run-all build deploy:surge",
Эта команда вводит в заблуждение. Предыдущее имя было лучше. Там понятно, что ты собираешься задеплоить именно в Surge. Тем более, что обе команды направлены именно на деплой в Surge

2017-03-22 07:39 UTC, Gebon commented on views/blocks/floatingButton/index.styl
> +    color $color-light
Я все-таки настаиваю на том, что переменная не должна описывать свое содержимое, а должна описывать свое предназначение. mainColor, secondaryColor, activeButtonColor, etc

2017-03-22 07:39 UTC, Gebon commented on .travis.yml
> +    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy'
Оставь как было. Сейчас, если в `npm run build` будет ошибка, сборка Travis все равно будет зеленой. А в предыдущей версии, сборка упадет. И, во-первых, ничего не задеплоится в Sruge, во-вторых, Heroku не обновит приложение.

2017-03-22 07:47 UTC, LeMarck commented on package.json
> -    "dev:server": "cross-env NODE_ENV=dev nodemon .",
Проблема в холиваре с `NODE_ENV`, так он прекратится

2017-03-22 07:51 UTC, LeMarck commented on .travis.yml
> +    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy'
Зачем делать сборку в ПР?

2017-03-22 07:55 UTC, Gebon commented on package.json
> -    "dev:server": "cross-env NODE_ENV=dev nodemon .",
Ну это не холивар. Нужно договориться и закончить его изменение. Я подумал, и это удаление действительно может иметь пользу. Давай уберем везде запуск с `NODE_ENV`, а в скриптах будет опираться на одно единственное условие `if (NODE_ENV

2017-03-22 07:59 UTC, LeMarck commented on package.json
> -    "dev:server": "cross-env NODE_ENV=dev nodemon .",
Если ты посмотришь этот коммит, то увидишь, что я так и сделал

2017-03-22 08:01 UTC, Gebon commented on .travis.yml
> +    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy'
Тогда, например, можно будет заранее знать, что есть проблема в сборке. И этот проблемный коммит не попадет в мастер.

Можно сделать по-другому: засунуть этот скрипт в `script`, тогда во время ПР сборки не будет, а когда задача попадет в мастер при проблемах со сборкой или деплоем сборка Travis упадет, и Heroku не обновит приложение.

2017-03-22 08:03 UTC, Gebon commented on package.json
> -    "dev:server": "cross-env NODE_ENV=dev nodemon .",
Огонь! Если бы это сразу рассказал, мы бы не потратили на это время. А как ты смотришь на то, чтобы в комментарии к ПР

2017-03-22 08:38 UTC, Gebon commented on .travis.yml
> +    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run build'
Чтобы не было ошибки, можно написать `[ "${TRAVIS_PULL_REQUEST}" = "true" ] && true || npm run build`

2017-03-22 08:40 UTC, Gebon commented
Я объяснил, почему не нужно каждый раз схлапывать в один коммит. В чем проблема?

2017-03-22 11:20 UTC, gallyamb requested changes
А можно всем ошибкам от stylint дать уровень ERROR? Чтобы Travis не проходил сборку при любом несоответствии

2017-03-22 11:20 UTC, Gebon commented on .travis.yml
> +    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run build'
Давай все же засунем в scripts, чтобы Travis падал при ошибках сборки статики? Просто сделаем `[ "${TRAVIS_PULL_REQUEST}" = "true" ] && true || npm run build`. До этого он упал, потому что `[ "${TRAVIS_PULL_REQUEST}" = "false" ]` вернул `false`, что в терминах Linux означает ненулевой exit code. А таким способом при ПР выполняется код ` && true`, и вернется 0, иначе выполняется `npm run build`.

Вся эта чехарда нужна, чтобы в мастер не попал и в Heroku с Surge не деплоился нерабочий код

2017-03-22 11:35 UTC, Gebon commented on .travis.yml
> +    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run build'
При ошибке в командах из секции `scripts` вся сборка Travis фейлится и становится красной. Как итог, соответствующий ПР не сможет быть смерджен. В нашем случае это значит, что если при сборке статики есть ошибки, то ПР не пройдет.

А вот ошибки в секции `after_success` уже не влияют на успешность билда. Это значит, что даже если при сборке статики произошла ошибка, мы об этом не узнаем. Более того, когда этот код будет закоммичен в мастер, эта сборка опять зафейлится, но деплой в Surge пройдет (задеплоятся потенциально невалидные файлы)

2017-03-22 12:53 UTC, IrinaSed reviewed
Может лучше будет если описание будет выдвигаться по ховеру? Или хотя бы если нажимаем на один, то все остальные скрывались?

2017-03-22 13:06 UTC, Gebon commented
Точно, совсем забыл про это. Описание по ховеру действительно было бы лучше

2017-03-22 13:27 UTC, Gebon commented
Я имел в виду при ховере на весь квест. И высоту побольше

2017-03-22 13:31 UTC, Gebon commented
Еще предлагаю после 560px скрывать маленькую картинку

2017-03-23 10:38 UTC, gallyamb submitted a review, later dismissed
Не серчай на замечания)

2017-03-23 10:38 UTC, gallyamb commented on views/blocks/questPreview/index.styl
> +$quest-preview-height = 200px
Может поменяем на `300px`? На больших экранах смотрится слишком мелко. Могу скинуть скрин с 1440х900

2017-03-23 10:38 UTC, gallyamb commented on views/blocks/questPreview/index.styl
> +    min-width 300px
Эту штуку нужно как-то доработать. На некоторых разрешениях (640х360) Описание квеста становится больше, чем правая картинка.

2017-03-23 10:38 UTC, gallyamb commented on views/pages/main/index.styl
> +      z-index -1
Может уберем эти три строки?
```stylus
position absolute
bottom 16px
z-index -1
```

Или доработаем как-то. Я так понимаю, они нужны для того, чтобы закрытая менюшка не занимала то же место, что и открытая. Но из-за этих трех строк анимация закрытия меню становится дерганой. Я не смог сходу придумать решение, поэтому предложил просто убрать. Кажется, что даже если меню будет занимать место, пользователю это не сильно помешает. Как думаешь?

2017-03-23 10:38 UTC, Gebon commented on views/blocks/questPreview/index.js
> +        elem.addEventListener('touchstart', () => {
Я обнаружил, что `touchstart` выглядит не очень красиво, например, когда пытаешься поскроллить страницу и палец попадает на описание, то описание начинает выдвигаться, а хочется по клику. Написал немного кода. Кажется так лучше, что скажешь?
```js
'use strict';

module.exports = () => {
    function nearby(startPosition, endPosition) {
        return Math.sqrt(Math.pow(endPosition.x - startPosition.x, 2) + Math.pow(endPosition.y - startPosition.y, 2)) < 5;
    }
    const elems = [...document.querySelectorAll('.quest-preview-description')];

    const change = position => {
        elems.forEach((elem, index) => {
            if (position !== index) {
                elem.dataset.visible = 'false';
            }
        });
    };

    elems.forEach((elem, index) => {
        elem.addEventListener('touchstart', event => {
            const touch = [...event.targetTouches][0];
            event.currentTarget.touchStartPosition = {
                x: touch.screenX,
                y: touch.screenY
            };
        });
        elem.addEventListener('touchend', event => {
            const touch = [...event.changedTouches][0];

            const position = {
                x: touch.screenX,
                y: touch.screenY
            };

            if (nearby(position, event.currentTarget.touchStartPosition)) {
                elem.dataset.visible = elem.dataset.visible === 'true' ? 'false' : 'true';
                change(index);
            }
        });
    });
};
```

2017-03-23 10:38 UTC, Gebon commented on README.md
> +| npm run deploy | Деплой статики в *Surge* |
`deploy:surge`?

2017-03-23 10:38 UTC, Gebon commented on index.js
> +if (process.env.NODE_ENV !== 'production') {
Еще раз, давай для не продакшена использовать логгер `dev`, а для продакшена другой, скажем`short`?

2017-03-23 13:09 UTC, IrinaSed approved these changes

2017-03-23 14:56 UTC, Gebon commented on views/blocks/questPreview/index.styl
> +    min-width $quest-preview-height
Меня немного смущает то, что свойство `width` связано с переменной `height`. Может выделить это в отдельную переменную?

2017-03-23 15:01 UTC, Gebon commented on views/blocks/floatingMenuButton/index.styl
> +      z-index -1
Объясни, почему это оставляем? Без этих трех строк анимация работает, а с ними нет. Я, видимо, чего-то не понимаю

2017-03-23 15:02 UTC, Gebon commented
А, давай еще стрелку на description добавишь?

2017-03-23 15:45 UTC, merged