#48. Добавил простые контроллеры
urfu-2016/team3 pull request #56
Opened 2017-03-24 15:19 UTC by Gebon

Пока что вместо моделей заглушка. Так же добавил стрелку в превью.

Без `registerWatchedPartials` сервер не всегда видит изменения во view.

2017-03-24 16:17 UTC, LeMarck submitted a review, later dismissed
![](https://pp.userapi.com/c638618/v638618658/88e27/ivfHezBMS6w.jpg)

**Всё к чёрту поехало**

2017-03-24 16:20 UTC, Gebon commented
@LeMarck свои ошибки можешь поправить сам. Разрешаю)

2017-03-24 16:32 UTC, LeMarck requested changes

2017-03-24 16:32 UTC, LeMarck commented on controllers/photos.js
> +        res.render('photo', Object.assign({photo: photo}, res.locals));
А зачем `Object.assign()` для рендеринга?
Чем плох вариант просто передать `{photo: photo}` вторым параметром?

2017-03-24 16:36 UTC, Gebon commented on controllers/photos.js
> +        res.render('photo', Object.assign({photo: photo}, res.locals));
В res.locals могут и, более того, лежат дополнительные данные для рендеринга страниц

2017-03-24 16:47 UTC, LeMarck commented on controllers/photos.js
> +        res.render('photo', Object.assign({photo: photo}, res.locals));
Всё что есть в *res.locals* уже доступно в шаблоне. Его не надо тупа передавать.

2017-03-24 16:50 UTC, Gebon commented on controllers/photos.js
> +        res.render('photo', Object.assign({photo: photo}, res.locals));
Тогда бессмысленно, конечно. Переделаю

2017-03-24 16:52 UTC, LeMarck commented
В **questPreview/index.styl**
```styl
&__title
   font-weight 600
   font-size 1.2rem
   margin 0
```
замени на
```stylus
&__title
  font-weight 600
  font-size 1.2rem
  margin 0
  text-overflow ellipsis
  overflow hidden
  white-space nowrap
  padding-right 10px
```

2017-03-24 16:57 UTC, Gebon commented
Пиши как комменты к коду, тут нет поля для ответа.

Думаю, что скрывать от пользователя заголовок вообще не круто. Предлагаю ограничить заголовок 30 символами и доделать верстку, чтобы заголовок всегда был виден

2017-03-24 17:06 UTC, LeMarck commented
Вообще-то этот код **не скрывает заголовок**, а аккуратно **обрезает, заменяя в конце на многоточие**.
Я бы с удовольствием указал это прямо в коде, но так как эта часть не была изменена, добавить к ней коммент не могу.

![image](https://cloud.githubusercontent.com/assets/11532954/24305227/0d487f1c-10de-11e7-8933-ac5027dccbfb.png)

2017-03-24 17:13 UTC, Gebon commented
Если с телефона, то да, там никак не оставишь коммент. Это аккуратное обрезание и скрывает от пользователя заголовок. Заходишь такой на сайт и видишь "Интересные места Ек...", и, пока не перейдешь по ссылке, не узнаешь, что же там написано. Вот это не круто

2017-03-24 17:50 UTC, svl96 commented
Стрелка, не очень органично смотрится. Без стрелки меня устраивало на данный момент, но если ее делать, то в любом случае по-другому (встраивать в затемненную плашку). А лучше пока убрать мне кажется.  Обрывок заголовка конечно тоже сомнительно. Пока правда не могу представить как будет смотреться, если отображать весь заголовок.

2017-03-24 18:51 UTC, Gebon commented
Что ж, уже два человека не видят необходимости в стрелке. Предлагаю тогда провести тестирование: взять скрин со стрелкой и без, найти двадцать максимально случайных людей, разделить их на две группы и каждой показать один из двух вариантов. Постановка вопроса: учитывая, что это сайт, куда можно кликнуть на картинке. Если вариант без стрелки будет статистически значимо отличаться от варианта со стрелкой в сторону уменьшения кликов по описанию, то стрелка определенно нужна, иначе выбрасываем ее к черту.

В текущем варианте встроить стрелку в плашку нельзя, потому что там название квеста. 

Я спросил у двух людей, куда можно кликнуть на сайте, и ни один пока не угадал, что эта плашка кликабельна. Так что смысл в тестировании есть.

Можно, конечно, забить на это и решить большинством голосов. Тогда ждем @IrinaSed и @Grehhov

2017-03-25 19:17 UTC, Gebon commented
Не понимаю, кто удаляет комменты. Дубль два к ревью @LeMarck про "все поехало": свои ошибки можешь поправить сам, разрешаю

2017-03-27 16:00 UTC, svl96 approved these changes

2017-03-30 01:48 UTC, LeMarck requested changes

2017-03-30 01:48 UTC, LeMarck commented on models/quest.js
> +        this.creationDate = Date.now();
Чем плох `new Date()` который возвращает текущую дату в понятном формате, а не какие-то циферки?

2017-03-30 01:48 UTC, LeMarck commented on .eslintrc.json
>    },
В чём проблема сделать один `.eslintrc.json` с правилами, а не плодить их для каждой папки?

2017-03-30 01:48 UTC, LeMarck commented on models/photo.js
> +    successfulTriesCount: {type: Number, default: 0},
Здесь и далее, определись с кодстайлом!

2017-03-30 01:48 UTC, LeMarck commented on views/blocks/searchForm/index.styl
> +  align-items stretch
`stretch` - значение по умолчанию

2017-03-30 02:55 UTC, Gebon commented on .eslintrc.json
>    },
Потому что нужно, чтобы у папок были разные настройки. Если умеешь делать в одном файле, поделись знанием

2017-03-30 02:56 UTC, Gebon commented on models/photo.js
> +    successfulTriesCount: {type: Number, default: 0},
Здесь и далее поясняй свою мысль!

2017-03-30 02:57 UTC, Gebon commented on views/blocks/searchForm/index.styl
> +  align-items stretch
Полагаться на значения по умолчанию не самый лучший выбор

2017-03-31 06:29 UTC, Gebon commented
@LeMarck самое время закончить ревью

2017-03-31 06:37 UTC, LeMarck approved these changes

2017-03-31 06:44 UTC, Gebon commented
@LeMarck, я имел в виду закончить начатое обсуждение. Но если ты считаешь, что уже все норм, то ок. Правда я все равно не понял про

2017-03-31 06:46 UTC, LeMarck commented
Просто ты в одном месте каждое свойство пишешь с новой строки, а в другом месте всё в одну строку.

2017-03-31 06:50 UTC, Gebon commented
Ну так все упирается в читаемость ведь. Писать объекты с один-тремя маленькими свойствами в несколько строк не видится необходимостью, потому что и так хорошо читается, а все, что больше, приходится разворачивать, потому что невозможно без напряга прочитать. Но я тебя понял, и, в принципе, согласен. Тогда нужно еще и правило для eslint сделать, чтобы везде описания объектов были одинаковыми

2017-03-31 06:54 UTC, LeMarck commented
А ещё, часть правок сделана относительно закрытого PR @IrinaSed, которому ты дал своё одобрение. А теперь у себя занимаешься ренеймингом и рассановкой переносов.

2017-03-31 07:03 UTC, Gebon commented
Ничего не поделаешь, не всегда все можно увидеть сразу)

2017-03-31 07:03 UTC, Gebon commented
Ты же не хочешь сказать, что после написания код трогать категорически нельзя?

2017-03-31 07:07 UTC, Gebon commented
Я не смог найти нормального правила ESLint для того, что хочется видеть. Если знаешь, подскажи. `object-curly-newline` делает не совсем то, что хочется

2017-03-31 07:31 UTC, merged