Closes #48 Создала модели и связала с бд
urfu-2016/team3 pull request #57
Opened 2017-03-24 20:55 UTC by IrinaSed

2017-03-25 06:29 UTC, gallyamb requested changes

2017-03-25 06:29 UTC, Gebon commented on models/connection.js
> +        const dbUser = 'MentionBot-Team3';
Думаю, что это плохая идея - хардкодить connection string. Лучше в проде брать полностью из переменной окружения.

2017-03-25 06:29 UTC, Gebon commented on models/user.js
> +    questLikes: [{type: ObjectId, ref: 'Quest'}],
likedQuests?

2017-03-25 06:29 UTC, Gebon commented on tests/models/photo-test.js
> +            id: 1,
ID mongo задает сама. Нужно без него сохранять. Иначе нам придется тратить ресурсы на поддержание уникальности

2017-03-25 06:29 UTC, Gebon commented on models/photo.js
> +    location: String,
Предлагаю заменить на обычные longitude/latitude с типом Number, раз в монге нет для этого специального типа

2017-03-25 06:29 UTC, Gebon commented on models/user_follower.js
> +    followedUserId: [{type: ObjectId, ref: 'User'}]
А почему это массив? Должен же быть как у userId. Иначе весь профит от вынесения в отдельную таблицу пропадает

2017-03-25 06:29 UTC, Gebon commented on models/user_follower.js
> +    followedUserId: [{type: ObjectId, ref: 'User'}]
Еще, я думаю, стоит сразу добавить индексы на каждое поле в отдельности

2017-03-26 12:51 UTC, LeMarck commented on models/photo.js
> +    location: String,
Моё предложение: `location: String` → `geo: Array`
А потом записывать как `[longitude, latitude]`

2017-03-26 14:34 UTC, Gebon commented on models/photo.js
> +    location: String,
Согласен, правильнее держать связанные сущности в одном объекте. `location` более выразительное название, не находишь? А тип сделать `{ longitude: Number, latitude: Number }`, потому что из массива непонятно, что есть что.

2017-03-27 04:37 UTC, gallyamb requested changes

2017-03-27 04:37 UTC, Gebon commented on models/photo.js
> +    questId: {type: ObjectId, ref: 'Quest', unique: true},
А почему unique? Несколько фотографий относятся к одному квесту ведь

2017-03-27 04:37 UTC, Gebon commented on models/quest.js
> +    authorId: {type: ObjectId, ref: 'User', unique: true},
Тут тоже. У разных квестов может быть один автор

2017-03-27 04:37 UTC, Gebon commented on models/user.js
> +    likedQuests: [{type: ObjectId, ref: 'Quest', unique: true}],
А как эти unique действуют в массивах? Кажется, что здесь они тоже излишни

2017-03-27 04:37 UTC, Gebon commented on models/user_follower.js
> +    userId: {type: ObjectId, ref: 'User', unique: true},
Тут они точно не unique, потому что эта таблица спроектирована так, что нужно хранить много записей с одинаковыми userId/followedUserId.

2017-03-27 04:37 UTC, Gebon commented on models/connection.js
> +    mongoose.connect(connectionString, {}, () => {
Может все же будем проверять на наличие ошибок? err => {}

2017-03-27 04:37 UTC, Gebon commented on models/connection.js
> +        connectionString = `mongodb://${dbUser}:${dbPassword}@${dbHost}/photoquests`;
Я имел в виду брать из окружения всю строку, а не складывать ее самим. Тут получается нужны три разных переменных, плюс база данных захардкожена

2017-03-28 18:50 UTC, gallyamb requested changes

2017-03-28 18:50 UTC, Gebon commented on models/connection.js
> +            console.log('CONNECTION ERROR!');
`console.error`

2017-03-28 18:50 UTC, Gebon commented on models/connection.js
> +            console.log('Connected to db');
`console.info`

2017-03-28 18:50 UTC, gallyamb approved these changes

2017-03-29 04:58 UTC, Gebon commented on models/connection.js
> +            console.error('CONNECTION ERROR!');
Я сразу не додумался. Тут еще нужно объект ошибки передать вторым аргументом, чтобы видеть стектрейс.

2017-03-29 04:58 UTC, Gebon commented on models/connection.js
> +        connectionString = process.env.connectionString;
А давай будем брать из переменной `MONGODB_URI`? Heroku mLab add-on представляет такую же переменную, если вдруг захотим использовать его, то ничего менять не придется

2017-03-29 05:16 UTC, LeMarck approved these changes

2017-03-29 05:16 UTC, LeMarck commented on models/quest.js
> +});
Может добавить в схему не только **кол-во людей выполняющих квест** и **кол-во завершивших**, чтобы можно было выводить статистику - *56/231*

2017-03-29 05:16 UTC, LeMarck commented on models/user.js
> +});
А для пользователя - *подписчики* и *подписки*, а так же сделать 2 счётчика - *активный* и *завершённый* кесты

2017-03-29 05:21 UTC, IrinaSed commented on models/user.js
> +});
У нас есть отдельная таблица follow_user, а для активный, не активный в модель отдельное поле мне кажется не нужно, мы сможем passedQuests, пройден квест или нет

2017-03-29 06:16 UTC, merged