#49 Auth conf
urfu-2016/team3 pull request #62
Opened 2017-03-30 17:41 UTC by svl96

2017-03-31 06:00 UTC, gallyamb requested changes

2017-03-31 06:00 UTC, Gebon commented on controllers/auth.js
> +    console.log('get login page');
Этот лог действительно нужен?

2017-03-31 06:00 UTC, Gebon commented on controllers/auth.js
> +    const hashPasword = crypto.createHash('sha256', process.env.hashSecret)
Давай для единообразия переменные среды писать большими буквами через нижнее подчеркивание: `process.env.HASH_SECRET`

2017-03-31 06:00 UTC, Gebon commented on controllers/auth.js
> +    console.log(user.username);
К этим логам тот же вопрос. Если хочется что-то логировать, что в продакшене не очень нужно, можно пользоваться `console.debug`

2017-03-31 06:00 UTC, Gebon commented on controllers/auth.js
> +    // сохранить пользователя ВК
А в чем проблема уже сейчас сохранять пользователя?

2017-03-31 06:00 UTC, Gebon commented on controllers/auth.js
> +    user.save((err) => {
Это нужный код?

2017-03-31 06:00 UTC, Gebon commented on index.js
> +app.use(session({secret: 'keyboard cat', saveUninitialized: false, resave: false}));
Может здесь секрет тоже из окружения брать?

2017-03-31 06:00 UTC, Gebon commented on index.js
> +app.use(passport.session());
А чем отличается обычная сессия и сессия паспорта?

2017-03-31 06:00 UTC, Gebon commented on passport.config.js
> +const VK_KEY = process.env.vkKey;
Здесь тоже именование

2017-03-31 06:00 UTC, Gebon commented on passport.config.js
> +    'http://localhost:8080/login/vkontakte/callback';
Это нужно явно переделать. Не нужно хардкодить

2017-03-31 06:00 UTC, Gebon commented on passport.config.js
> +    done(null, user); // добавляю по имени, пока не генерится id при добавлении в БД
id генерируется ведь?

2017-03-31 06:00 UTC, Gebon commented on passport.config.js
> +    console.log('serializing' + JSON.stringify(user));
Еще один лог

2017-03-31 06:00 UTC, Gebon commented on passport.config.js
> +            const hashPassword = Crypto.createHash('sha256', process.env.hashSecret)
Эту строку я уже видел. Нужно внести

2017-03-31 06:00 UTC, Gebon commented on views/pages/login/index.hbs
> +<!DOCTYPE html>
Это я смотреть не буду, потому что наверняка переверстают)

2017-03-31 06:32 UTC, IrinaSed commented on passport.config.js
> +require('./auth.config');
А где у тебя модуль auth.config?

2017-03-31 07:13 UTC, Gebon commented on passport.config.js
> +require('./auth.config');
Подозреваю, что он в .gitignore, потому что там должна находиться чувствительная информация

2017-04-03 18:43 UTC, IrinaSed commented on passport.config.js
> +require('./auth.config');
Дак если смержим, у нас в мастере ничего работать не будет

2017-04-08 18:58 UTC, IrinaSed commented on .gitignore
> +auth.config.js
нужно его отсюда убрать

2017-04-10 10:34 UTC, gallyamb requested changes

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +exports.loginLocal = (req, res, next) => {
Можно просто
```js
exports.loginLocal = passport.authenticate('local', {
  successRedirect: '/',
  failureRedirect: '/login?fail=true'
});
```

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +    user.save(err => {
Я предлагаю обрабатывать всю асинхронщину по возможности в Promise-стиле.
```js
user.save()
  .then(user => { /* do something with user */ })
  .catch(next);
```

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +        User.findOne({name: username}, (err, user) => {
Здесь тоже Promise

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +exports.loginVK = (req, res, next) => {
Тоже можно упростить

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +exports.loginVKCallback = (req, res, next) => {
И это

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +    User.findOne({vkID: profile.id}, (err, user) => {
Promise

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +exports.vkStrategy = (VK_ID, VK_KEY) => (new VKStrategy({
А зачем внешние скобки?

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +exports.loginTwitterCallback = (req, res, next) => {
Упростить

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +exports.loginTwitter = (req, res, next) => {
Упростить

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +exports.twitterStrategy = (TWITTER_KEY, TWITTER_SECRET) => (
Внешние скобки?

2017-04-10 10:34 UTC, Gebon commented on controllers/auth.js
> +        User.findOne({twitterID: profile.id}, (err, user) => {
Promise

2017-04-10 10:34 UTC, Gebon commented on passport.config.js
> +    User.findById(id, (err, user) => {
`User.findById(id, done)`

2017-04-12 06:25 UTC, gallyamb requested changes

2017-04-12 06:25 UTC, Gebon commented on controllers/auth.js
> +exports.vkStrategy = (VK_ID, VK_KEY) => new VKStrategy({
А что ты думаешь насчет того, чтобы вынести все стратегии в отдельный модуль? Чтобы не смешивать разные сущности в одном файле (стратегии и код контроллеров)

2017-04-12 06:25 UTC, Gebon commented on index.js
> +app.use(session({secret: process.env.SESSION_SECRET}));
Я предлагаю все данные, которые мы получаем из окружения, складывать в отдельный файл, как в #65, чтобы логика того, где именно берется информация, была инкапсулирована в модуле. Дополнительный профит от этого: если вдруг имя переменной окружения изменится, в коде будет ровно одно изменение.

2017-04-12 06:25 UTC, Gebon commented on middlewares/common-data.js
> +        res.locals.username = req.user.name;
А может складывать сам объект `user`? Во вьюхах может понадобиться не только имя, я думаю

2017-04-12 06:25 UTC, Gebon commented on middlewares/isAuth.js
> +    return req.isAuthenticated() ? next() : res.redirect('/login');
Было бы классно здесь передавать еще и url откуда пользователя перенаправило, чтобы после его авторизации можно было обратно на нужную страницу перенаправить

2017-04-12 06:25 UTC, Gebon commented on models/user.js
> +userSchema.statics.createPasswordHash = password => {
А зачем это в statics? Используется только здесь

2017-04-12 06:25 UTC, Gebon commented on models/user.js
> +userSchema.virtual('passwordHash').set(password => {
А это значит, что после перезагрузки сервера все хеши пропадут?

2017-04-12 06:25 UTC, Gebon commented on package.json
> +    "crypto": "0.0.3",
Женя говорит, что `crypto` уже включён в Node.js

2017-04-12 06:25 UTC, Gebon commented on passport.config.js
> +    User.findById(id, (err, user) => {
?

2017-04-12 08:54 UTC, Gebon commented on index.js
> +app.use(session({secret: process.env.SESSION_SECRET}));
Хотя забей. Пока эта штука используется в одном месте, нет смысла ее трогать

2017-04-15 12:16 UTC, Gebon commented on package.json
> +    "crypto": "0.0.3",
Отбой. Node.js может быть и без него https://nodejs.org/api/crypto.html#crypto_determining_if_crypto_support_is_unavailable

2017-04-16 13:57 UTC, closed without merging