Closes #58. Add Google's reCaptcha support
urfu-2016/team3 pull request #65
Opened 2017-04-01 16:14 UTC by Gebon

Как заставить работать:
 * на каждый route, где необходимо включить проверку, нужно навесить дополнительный middleware `recaptcha.middleware.render`, который положит в `req.recaptcha` html представление капчи
 * пробросить это представление в `res.render`
 * во вьюхе отрендерить `{{{ captcha }}}`
 * на route обработчика формы навесить дополнительный middleware `recaptcha.middleware.verify`, который при ошибке проверки положит в `req.recaptcha.error` ошибку
 * далее в просто обработать наличие/отсутствие ошибки
 * на страницах, где рендерится капча, нужно добавить `<script src='https://www.google.com/recaptcha/api.js'></script>`

2017-04-03 18:55 UTC, IrinaSed commented
Чёт, у меня всё падает
if (!this.secret_key) throw new Error('secret_key is required');
                        ^

Error: secret_key is required

2017-04-04 08:34 UTC, Gebon commented
@IrinaSed comment updated

2017-04-06 07:10 UTC, Gebon commented
@IrinaSed @LeMarck уже пора делать ревью, кажется?)

2017-04-08 20:00 UTC, IrinaSed requested changes
Как-то не очень круто, что мне приходится прописывать SECRET_KEY, чтобы просто посмотреть всё ли работает, почему не сделать чтобы локально тоже работало?

2017-04-08 20:18 UTC, Gebon commented
Ты можешь написать себе скрипт, который будет устанавливать все эти переменные. А как ты хочешь заставить работать локально без секрета?

2017-04-08 20:25 UTC, IrinaSed commented
ну сделать пока чтобы не работало, если локально, как-то так, просто если я захочу просто посмотреть вёрстку, то мне придётся каждый раз устанавливать секрет

2017-04-09 07:18 UTC, Gebon commented
А, понял тебя. Да, над этим я подумаю

2017-04-09 07:46 UTC, Gebon commented
Решение: https://www.npmjs.com/package/dotenv

2017-04-11 14:04 UTC, IrinaSed approved these changes

2017-04-11 15:16 UTC, Grehhov commented on index.js
> +const captchaSettings = require('./configs/cpatcha');
./configs/cAPtcha

2017-04-11 15:19 UTC, Grehhov approved these changes

2017-04-12 07:39 UTC, merged