Closed #63 Fix Test
urfu-2016/team3 pull request #66
Opened 2017-04-03 18:19 UTC by IrinaSed

2017-04-04 05:13 UTC, gallyamb requested changes

2017-04-04 05:13 UTC, Gebon commented on tests/models/user-test.js
> +    after(() => User.remove({}).exec());
Думаю, что нужно добавить такие методы во все тесты, чтобы после тестов тестовые объекты не оставались в базах.
`after/beforeEach` нужно переделать так:
```js
after(done => somethingAsync.then(() => done())
```
Это нужно, чтобы `after/beforeEach` точно выполнилось до начала тестов/конца выполнения

2017-04-04 05:13 UTC, Gebon commented on models/user_follower.js
> +const mongoose = require('./connection');
А зачем создавать соединение с базой здесь (вообще в модели)?
Соединение должно устанавливаться явно.

2017-04-04 05:13 UTC, Gebon commented on models/connection.js
> +module.exports = mongoose;
Раньше было лучше. Соединение нужно устанавливать, когда этого захочет вызывающий код.

2017-04-05 03:19 UTC, IrinaSed commented on tests/models/user-test.js
> +    after(() => User.remove({}).exec());
Зачем так? Я просто могу после выполнения удалить User: 
after(() => User.remove({}).exec());

  beforeEach(() => User.remove({}).exec()); - это лишне, согласна

2017-04-05 07:34 UTC, Gebon commented on tests/models/user-test.js
> +    after(() => User.remove({}).exec());
`beforeEach` не лишний. Так нужно делать, потому что операции удаления аснихронные. Может так случиться, что тест начнется раньше, чем коллекция очистится. А так можно быть уверенным, что `beforeEach` действительно прошел полностью

2017-04-05 16:56 UTC, IrinaSed commented on tests/models/user-test.js
> +    after(() => User.remove({}).exec());
Базовых тестовых классов у моки нет ведь. А beforeEach и так перед всеми тестами вызывается. Плюс мока сама дожидается того, что в before, after и тп

2017-04-06 07:09 UTC, Gebon commented on tests/models/user-test.js
> +    after(() => User.remove({}).exec());
Не понял про базовые тестовые классы.

> А beforeEach и так перед всеми тестами вызывается

Название намекает)

> Плюс мока сама дожидается того, что в before, after и тп

Дожидается, только если это синхронный код/возвращается `Promise`. Насколько я понял, `exec` возвращает `Promise`, так что да, `done` не нужен.

2017-04-08 19:04 UTC, IrinaSed commented on tests/models/user-test.js
> +    after(() => User.remove({}).exec());
Я имею в виду, что тут нет наследования, как в других языках. Не получится написать базовый класс, в котором будет метод очищения базы

2017-04-08 19:27 UTC, IrinaSed commented on models/user_follower.js
> +const mongoose = require('./connection');
Нам нужно устанавливать соединение с базой один раз, если мы будем устанавливать в каждом тесте, то у нас получится что соединение будет устанавливаться несколько раз, если написать только в одном тесте, не сможем по отдельности запускать

2017-04-08 19:36 UTC, Gebon commented on tests/models/user-test.js
> +    after(() => User.remove({}).exec());
А разве об этом шла речь?

2017-04-08 19:36 UTC, Gebon commented on models/user_follower.js
> +const mongoose = require('./connection');
В `after` закрываешь соединение, в `before` открываешь. Ничего сложного

2017-04-08 19:38 UTC, IrinaSed commented on tests/models/user-test.js
> +    after(() => User.remove({}).exec());
я думала про это, ну ок поняла

2017-04-08 19:42 UTC, IrinaSed commented on models/user_follower.js
> +const mongoose = require('./connection');
`В after закрываешь соединение, в before открываешь. Ничего сложного`
так точно лучше?

2017-04-10 04:53 UTC, Gebon commented on models/user_follower.js
> +const mongoose = require('./connection');
Я думаю, что так лучше. Не всегда нужно соединятся с базой, когда используешь модели. Явное всегда лучше неявного

2017-04-10 11:45 UTC, LeMarck approved these changes

2017-04-10 11:45 UTC, LeMarck commented on models/user_follower.js
> +const mongoose = require('./connection');
Модели без соединения с базой никак не используются. Мне кажется хорошим вариант сделать `connect` к базе, а потом импортировать его в модели. Особенно когда несколько баз.

2017-04-10 12:23 UTC, Gebon commented on models/user_follower.js
> +const mongoose = require('./connection');
Модели без соединения с базой очень даже используются. Не на все тесты нужны настоящие соединения с базой.

2017-04-11 15:49 UTC, gallyamb approved these changes

2017-04-11 15:54 UTC, merged