Closed #60 Прикрутила комментарии
urfu-2016/team3 pull request #69
Opened 2017-04-05 16:54 UTC by IrinaSed

2017-04-05 17:04 UTC, gallyamb requested changes

2017-04-05 17:04 UTC, Gebon commented on models/quest.js
> +        parentCommetId: {type: ObjectId, ref: 'User'}
Comment

2017-04-05 17:04 UTC, Gebon commented on models/quest.js
> +        parentCommetId: {type: ObjectId, ref: 'User'}
Если уж делать иерархию, то нужно вынести это в отдельную модель. И ref = Comment

2017-04-11 18:58 UTC, Gebon commented on models/quest.js
> +        parentCommetId: {type: ObjectId, ref: 'User'}
А эта иерархия нам точно нужна? Может пока ограничимся обычными комментариями?

2017-04-11 19:15 UTC, IrinaSed commented on models/quest.js
> +        parentCommetId: {type: ObjectId, ref: 'User'}
Думаю да,  если уж делать коментарии,  то полноценные

2017-04-12 19:07 UTC, gallyamb requested changes
А где контроллер? Добавить только модель мало для этой задачи

2017-04-12 19:07 UTC, gallyamb commented on models/comment.js
> +    parentCommetId: {
`parentComment` (без id)

2017-04-12 19:07 UTC, gallyamb commented on models/comment.js
> +        required: false
Это уже по умолчанию

2017-04-12 19:07 UTC, gallyamb commented on models/comment.js
> +    authorId: {
`author`

2017-04-12 19:07 UTC, Gebon commented on models/quest.js
> +        CommentId: ObjectId
Это что-то странное. Наверно, ты хотела `comments: [{type: ObjectId, ref: 'Comment'}]`?

2017-04-12 19:07 UTC, Gebon commented on tests/models/comment-test.js
> +            .then(savedComment => assert.equal(savedComment.url, comment.url));
Ммм, копипаст

2017-04-16 12:25 UTC, gallyamb reviewed
Нужно убрать все, что связано с моделью `Comment`

2017-04-16 12:25 UTC, gallyamb commented on controllers/comments.js
> +module.exports = {
Давай сохранять один стиль. exports.list = function (...) {} и т.д.

2017-04-16 12:25 UTC, gallyamb commented on controllers/comments.js
> +        Comment.find((err, comments) => {
Promise

2017-04-16 12:25 UTC, gallyamb commented on controllers/comments.js
> +        comment.save((err, comment) => {
Promise

2017-04-16 12:25 UTC, gallyamb commented on controllers/comments.js
> +            author: req.body.author.id,
Что это за поле? Может req.user._id?

2017-04-16 12:25 UTC, gallyamb commented on controllers/comments.js
> +            parentComment: req.body.parentComment.id
_id

2017-04-16 12:25 UTC, gallyamb commented on controllers/comments.js
> +        Comment.findByIdAndRemove(req.params.id, (err, comment) => {
Promise

2017-04-16 12:25 UTC, gallyamb commented on models/comment.js
> +        required: false
Это не нужно указывать

2017-04-16 12:25 UTC, gallyamb commented on models/quest.js
> +        CommentId: ObjectId
?

2017-04-16 12:25 UTC, Gebon commented on models/quest.js
> +            required: false
true?

2017-04-16 18:13 UTC, gallyamb requested changes

2017-04-16 18:13 UTC, Gebon commented on scripts/clear-db.js
> +        return Promise.all([
Внешний массив тут не нужен, кажется

2017-04-16 18:13 UTC, Gebon commented on scripts/clear-db.js
> +    });
Может добавить еще catch с закрытием соединения?

2017-04-17 14:18 UTC, gallyamb requested changes

2017-04-17 14:18 UTC, Gebon commented on scripts/clear-db.js
> +            models.map(model => {
To shorthand func

2017-04-17 14:18 UTC, Gebon commented on scripts/clear-db.js
> +    .then(() => {
To shorthand func

2017-04-17 14:18 UTC, Gebon commented on scripts/clear-db.js
> +        return Promise.all([
Массив не нужен. Получается массив массивов промисов

2017-04-20 04:57 UTC, gallyamb requested changes

2017-04-20 04:57 UTC, Gebon commented on controllers/quests.js
> +            quest.comments.push({text: req.body.text, author: req.user});
А если такого квеста нет?

2017-04-20 04:57 UTC, Gebon commented on models/quest.js
> +        text: String,
Может ограничить комментарии какой-то разумной величиной? Как думаешь?

2017-04-20 08:13 UTC, LeMarck approved these changes

2017-04-20 08:13 UTC, LeMarck commented on views/pages/quest/index.hbs
> +    </form>
Может стоит поменять местами форму отправки комментария и список комментариев?

2017-04-20 11:56 UTC, gallyamb approved these changes

2017-04-20 11:57 UTC, merged