Enhanced image uploading
urfu-2016/team3 pull request #71
Opened 2017-04-07 10:35 UTC by Gebon

Это реализация той версии из комментариев #70 
#59

2017-04-10 11:55 UTC, LeMarck submitted a review, later dismissed

2017-04-10 11:55 UTC, LeMarck commented on package.json
> +    "http-status": "^1.0.1",
Не вижу смысла в этой библиотеке

2017-04-10 11:55 UTC, LeMarck commented on package.json
> +    "crypto": "0.0.3",
`crypto` есть и у node, не надо лишнее подключать

2017-04-10 11:55 UTC, LeMarck commented on db/connection-string.js
> +module.exports = process.env.MONGODB_URI || 'mongodb://localhost/photo-quest';
Можно все строки вынести в отдельные модули))

2017-04-10 12:20 UTC, Gebon commented on db/connection-string.js
> +module.exports = process.env.MONGODB_URI || 'mongodb://localhost/photo-quest';
Это было зачем-то нужно, но я уже забыл. Так что, видимо, не так уж оно и нужно)

2017-04-10 12:21 UTC, Gebon commented on package.json
> +    "http-status": "^1.0.1",
Descriptive naming в статусах вместо 404/500/301/201/etc

2017-04-10 12:21 UTC, Gebon commented on package.json
> +    "crypto": "0.0.3",
Не знал

2017-04-10 12:26 UTC, LeMarck commented on package.json
> +    "http-status": "^1.0.1",
Это лишь моё мнение, но куда проще просто поставить циферки, нежели тянуть для этого целую либу

2017-04-10 12:28 UTC, LeMarck commented on package.json
> +    "http-status": "^1.0.1",
К тому же у нас в основном всего 2 кода: 404 и 500. Если так охота, но вынеси их в нашу внутреннюю либу

2017-04-10 12:32 UTC, Gebon commented on package.json
> +    "http-status": "^1.0.1",
И потом, с увеличением использования кодов, напишем свою такую же либу?) Не понимаю проблему. Либа без зависимостей, маленькая по размеру. Нет причин не использовать ее

2017-04-10 12:36 UTC, LeMarck commented on package.json
> +    "http-status": "^1.0.1",
С любой я погорячился, но `404` куда короче, чем `HttpStatus.NOT_FOUND`

2017-04-10 12:51 UTC, Gebon commented on package.json
> +    "http-status": "^1.0.1",
Такое ощущение, что мы в коде только и делаем, что пишем http коды. Ничего страшного в том, что ты напишешь на пару символов больше (автодополнение поможет) нет. Главное в коде - это читаемость, а не то, насколько быстро ты его напишешь

2017-04-10 12:57 UTC, LeMarck commented on package.json
> +    "http-status": "^1.0.1",
По моему читабельно и 404 и Not Found. А многие мало распространенные коды не всегда понятны в любом написании. Но если ты прямо жить не можешь без этой либы, то пусть будет.

2017-04-11 14:39 UTC, Grehhov commented on controllers/quests.js
> +            if (true || quest.published || (req.user && quest.author === req.user._id)) {
Не забудь убрать true

2017-04-11 14:49 UTC, IrinaSed requested changes

2017-04-11 14:49 UTC, IrinaSed commented on controllers/photos.js
> +                                photoId: photo._id,
photo

2017-04-11 14:49 UTC, IrinaSed commented on models/quest.js
> -        required: true
обязательный

2017-04-11 14:49 UTC, IrinaSed commented on controllers/photos.js
> +        ) < 0.005;
почему именно 0.005

2017-04-11 14:50 UTC, Grehhov approved these changes

2017-04-12 08:29 UTC, Gebon commented on controllers/photos.js
> +        ) < 0.005;
Мы храним координаты в градусах (Signed degrees format (DDD.dddd)).

Чтобы узнать, оказался ли игрок рядом с тем местом на фотографии, которое он пытается зачекинить, нужно как-то ограничить место на земле, в котором мы будем принимать его координаты за успешное прохождение.

Из ссылок ниже можно узнать, что 1e-8 =~ 1mm на Земле, а 0.005 =~ 500m.

Теперь почему именно 500 метров: при создании квеста есть погрешность в геопозиции создателя, при прохождении есть погрешность у игрока. Т.е. даже если они встанут в одном месте, их позиция может существенно разниться. Я оценил эту существенную разницу в 500 метров.

http://www.geomidpoint.com/latlon.html
http://stackoverflow.com/questions/15965166/what-is-the-maximum-length-of-latitude-and-longitude

2017-04-12 08:53 UTC, LeMarck commented on controllers/photos.js
> +        ) < 0.005;
Geolib: https://github.com/manuelbieh/Geolib

2017-04-12 09:04 UTC, Gebon commented on controllers/photos.js
> +        ) < 0.005;
Годная либа

2017-04-12 09:20 UTC, Gebon commented
@LeMarck @IrinaSed прошу ревью

2017-04-12 18:25 UTC, IrinaSed approved these changes

2017-04-13 07:07 UTC, gallyamb commented on controllers/photos.js
> +            Quest
Use promise chaining

2017-04-13 07:07 UTC, gallyamb commented on controllers/photos.js
> +            User
Use promise chaining

2017-04-13 07:07 UTC, gallyamb commented on controllers/quests.js
>              return res.redirect('/quests/create');
Indicate error via query string

2017-04-13 07:07 UTC, gallyamb commented on db/connect.js
> +    return new Promise((resolve, reject) => {
Promise.resolve

2017-04-13 07:07 UTC, Gebon commented on routes/index.js
> +    ['common', 'user', 'quest', 'photo'].forEach(routeName => require(`./${routeName}`)(app));
Consider dynamically finding of the routers

2017-04-13 07:07 UTC, Gebon commented on routes/photo.js
> +    app.post('/photos/:id/checkin', recaptcha.middleware.verify, photos.checkin);
HTTP PUT

2017-04-13 07:07 UTC, Gebon commented on scripts/fill-db.js
> +    Promise.all(removePromises)
Promise chaining

2017-04-15 11:47 UTC, merged