Верстка страниц и блоков
urfu-2016/team3 pull request #73
Opened 2017-04-15 09:01 UTC by LeMarck

## Блоки

* **index** - глобальные стили и скрипты
* **button** - простая кнопка
* **description** - описание квеста
* **edit_text** - текстовое поле
* **floating_button** - кнопка в стиле *Material Design*
* **floating_menu** - меню в стиле *Material Design*
* **header** - шапка сайта
* **quest_card** - карточка квеста
* **quest_description** - описание квеста
* **quest_point** - места которые надо найти
* **quest_checkin** - чекин
* **search_form** - поиск
* **sort_panel** - панель сортировки

## Страницы

* **main** - доработка
* **quest** - квест :)
* **login** - авторизация
* **join** - регистрация

## Прочее

Обновил **hbs-helpers**

2017-04-15 10:44 UTC, gallyamb requested changes
* На главной `opacity` меняется резко. Нужен `transition`
 * Блок логина\регистрации очень слабо выделен ![login](https://cloud.githubusercontent.com/assets/5419623/25062990/f046d362-21f1-11e7-9c8c-8976c7d8d420.PNG)
 * Длинные слова ломают верстку ![long-words](https://cloud.githubusercontent.com/assets/5419623/25062994/fe35e648-21f1-11e7-8dd3-9ce5ff29cd37.PNG)
 * Нужна минимальная высота к описанию блока ![min-height1](https://cloud.githubusercontent.com/assets/5419623/25062996/09f5e0fa-21f2-11e7-888d-2f4dff512659.PNG) ![min-height2](https://cloud.githubusercontent.com/assets/5419623/25062998/0dbfe3e8-21f2-11e7-9860-6082d8bfb795.PNG)
 * Превью фоток больше, ничего не видно ![photo-preview](https://cloud.githubusercontent.com/assets/5419623/25063001/211467b6-21f2-11e7-8a9e-34eb1c709c1c.PNG)
 * На мобилках превью на всю ширину может сделать? Зачем нагромождать ![mobile-photo-preview](https://cloud.githubusercontent.com/assets/5419623/25063002/2addbf0e-21f2-11e7-999a-cc6c9a9231b3.PNG)
 * Фотку в превью центрировать вертикально ![vertically-center](https://cloud.githubusercontent.com/assets/5419623/25063005/42ba85ee-21f2-11e7-8570-4de16fc23acc.PNG)

2017-04-15 10:44 UTC, gallyamb commented on index.js
> +    recaptcha.init(captchaSettings.siteKey, captchaSettings.secretKey, {theme: 'dark'});
Эта штука должна инициализироваться всегда

2017-04-15 10:44 UTC, gallyamb commented on utils/hbs-helpers.js
> +    return array[0];
А если массив `undefined || null`?

2017-04-15 10:44 UTC, gallyamb commented on utils/hbs-helpers.js
> +    return array[array.length - 1];
А если массив `undefined || null`?

2017-04-15 10:44 UTC, gallyamb commented on views/README.md
> +:warning: **Внимание! Не трогайте блоки!**
Довольно странное предупреждение. Не ты владеешь блоками, а вся команда. А значит и любой может его изменять. Думаю, что лучше пояснить, почему ты не хочешь их изменения.

2017-04-15 10:44 UTC, gallyamb commented on views/blocks/index/geolocation.js
> +        const error = err => {
Эта функция не нужна, т.к. можно сразу передать `reject`

2017-04-15 10:44 UTC, gallyamb commented on views/blocks/index/geolocation.js
> +        const success = position => {
Вынеси эту функцию в верхний уровень. Сейчас при каждом вызове `geolocation()` создается новая функция, а это ни к чему

2017-04-15 10:44 UTC, Gebon commented on views/blocks/photocards/index.hbs
> +<section class="photo-cards">
А почему только 3 фотки?

2017-04-15 10:44 UTC, Gebon commented on views/blocks/quest_description/index.hbs
> +                {{> floating_button/default _icon='add' }}
А что делает follow для квеста? Другой иконки нет? Я пока в код не зашел, не понял, что делает эта кнопка.

2017-04-15 10:44 UTC, Gebon commented on views/blocks/quest_description/index.hbs
> +                {{> floating_button/default _icon='add' }}
Точно такая же кнопка была бы здесь к месту, когда квест еще не опубликован. Чтобы автор мог добавить новую фотку.

2017-04-15 10:44 UTC, Gebon commented on views/blocks/sort_panel/index.js
> +    const virtualDiv = document.createElement('div');
Пока что, конечно, пофиг. Но в будущем это все должно будет делаться на сервере (я имею в виду сортировку)

2017-04-15 10:48 UTC, Gebon commented
ПР сломал нашего Капитана :D

2017-04-15 18:58 UTC, LeMarck commented on index.js
> +    recaptcha.init(captchaSettings.siteKey, captchaSettings.secretKey, {theme: 'dark'});
А зачем нам *recaptcha* в **dev**?

2017-04-15 19:05 UTC, LeMarck commented on views/README.md
> +:warning: **Внимание! Не трогайте блоки!**
**Я отвечаю за вёрстку**. И мне не охота смотреть PR которые ломают блоки
> Я тут подумал, мне не нравится название переменной, мой дзен говорит, что она должна называться так

Для всех блоков я добавил **README.md** c описание. Если вдруг так случится, что нужно поправить блок, то следует написать об этом в **Issue** и создать для этого **отдельный PR**.

Взаимодействие блока с сервером происходит по средствам `pages` там делайте что хотите, но в разумных пределах.

2017-04-15 19:08 UTC, LeMarck commented on views/blocks/photocards/index.hbs
> +<section class="photo-cards">
А почему бы и нет? В чём проблема? Это декоративный блок, цель которого разукрасить страницу авторизации.

2017-04-15 19:14 UTC, LeMarck commented on views/blocks/quest_description/index.hbs
> +                {{> floating_button/default _icon='add' }}
"+" по моему очень даже семантичен. Добавить (подписаться) на квест.
Небольшие манипуляции превращают страницу показа квеста в страницу его создания.

2017-04-16 03:36 UTC, Gebon commented on views/blocks/photocards/index.hbs
> +<section class="photo-cards">
А, я почему-то подумал, что это фотки на странице квеста

2017-04-16 03:39 UTC, Gebon commented on index.js
> +    recaptcha.init(captchaSettings.siteKey, captchaSettings.secretKey, {theme: 'dark'});
Затем, что это часть приложения. Так можно дойти до абсурда и выключить авторизацию ВК/твиттера, капчу и другие функции, ссылаясь на "зачем это в разработке".

2017-04-16 03:42 UTC, LeMarck commented on views/blocks/photocards/index.hbs
> +<section class="photo-cards">
Решил вынести как повторяющийся блок. Идея: рендомить 3 случайные фотки и показывать их

2017-04-16 03:44 UTC, Gebon commented on views/README.md
> +:warning: **Внимание! Не трогайте блоки!**
Ну нет, так не пойдет. Блоки будут менять не только ты. Каждый, кому понадобится изменить блок, будет это делать, а ты будешь это ревьюить. Ревью для того и сделано, чтобы все могли быть довольны кодом (в какой-то степени), который попадает в мастер. А твоя идея с issue -> pr только затягивает и так не быструю разработку

2017-04-16 03:47 UTC, Gebon commented on views/blocks/quest_description/index.hbs
> +                {{> floating_button/default _icon='add' }}
Мне, конечно, плюс не показался понятным, но спросить об этом не буду. Если выяснится, что это и правда плохая иконка, всегда можно поменять

2017-04-16 03:48 UTC, Gebon commented on views/blocks/photocards/index.hbs
> +<section class="photo-cards">
Это прикольно)

2017-04-16 04:14 UTC, Gebon commented
Ты как-то не очень хорошо ребейзнулся. Вижу как минимум роуты. Думаю, что это на хакатоне обсудим

2017-04-16 08:43 UTC, gallyamb requested changes

2017-04-16 08:43 UTC, Gebon commented on package.json
> +    "lint:js": "eslint . --fix",
Мне кажется эта штука только мешает. Все-таки хочется делать правки самостоятельно. Бывает, что нужно сделать иначе, чем считает линтер

2017-04-16 08:50 UTC, IrinaSed approved these changes

2017-04-16 08:54 UTC, Grehhov approved these changes

2017-04-16 08:56 UTC, gallyamb approved these changes

2017-04-16 09:00 UTC, merged