Closes #23 Страница создания квеста
urfu-2016/team3 pull request #76
Opened 2017-04-16 11:29 UTC by Grehhov

2017-04-16 12:21 UTC, IrinaSed reviewed
Может быть всё таки переделать форму с описанием квеста, чтобы если текста слишком много появлялся скролл и нельзя было растягивать границу, либо, чтобы можно было растягивать, но тогда при этом форма автоматически растягивалась при большом количестве текста???

2017-04-16 18:14 UTC, Gebon commented
А мне кажется, что нужно оставить возможность менять размер поля ввода. Зачем ограничивать?

2017-04-16 18:33 UTC, gallyamb requested changes

2017-04-16 18:33 UTC, Gebon commented on views/blocks/create_quest/index.hbs
> +    <form class="create-quest__form" method="post">
Action?

2017-04-17 19:16 UTC, Grehhov commented
Блок теперь по центру, и поэтому если изменять размер textarea, то получится не очень красиво (блок будет двигаться вверх), поэтому предложение ограничить, оказалось, по-моему, вполне разумным.

2017-04-18 03:22 UTC, Gebon commented
Я думаю, что нужно убрать box-shadow на мобиле. Визуально обрывает страницу, а зачем - непонятно
![screenshot_2017-04-18-08-19-44-680_com android chrome](https://cloud.githubusercontent.com/assets/5419623/25113347/15bfba30-2410-11e7-94e1-718a1fe67112.png)

2017-04-18 03:25 UTC, gallyamb requested changes
Рендерить капчу

2017-04-18 09:50 UTC, Gebon commented
Как по мне, так лучше с возможностью менять высоту. Можно сделать ограничение по высоте, чтобы пользователь не мог слишком сильно расширить и поломать верстку. Предлагаю обсудить это очно

2017-04-21 02:42 UTC, Gebon commented
Обновись на мастер, а то я не могу зайти в приложение и посмотреть его. Ну или сделай что-нибудь, чтобы review app поднялось

2017-04-21 04:27 UTC, Gebon commented on views/pages/createQuest/index.styl
> +.big-text__textarea_max-height
Селектор не очень по БЭМ. Я бы выбрал big-text__textarea_limited-height. Это просто к информации, править не обязательно

2017-04-21 05:43 UTC, gallyamb approved these changes

2017-04-22 19:38 UTC, IrinaSed approved these changes

2017-04-23 05:00 UTC, merged