Add authorization ability
urfu-2016/team3 pull request #77
Opened 2017-04-16 13:28 UTC by Gebon

2017-04-17 09:13 UTC, gallyamb commented on auth/vk-strategy.js
> +        email: params.email,
Remove

2017-04-17 09:13 UTC, gallyamb commented on configs/passport.js
> +    twitterStrategy(env.TWITTER_KEY, env.TWITTER_SECRET));
Remove `lf`

2017-04-17 09:13 UTC, gallyamb commented on controllers/quests.js
> +        .populate('photos')
**ОЧЕНЬ** дорогая операция. Нужно будет когда-нибудь поправить. Не забыть завести issue

2017-04-17 09:13 UTC, Gebon commented on index.js
> +app.set('trust proxy', true);
Предугадывая вопрос "Зачем это нужно?": наше приложение хостится в Heroku, который имеет `https`, но если мы зайдем по `http`, то ничего не изменится, только приложение уже будет работать в незащищенной среде. Чтобы этого избежать, я написал middleware для автоматического перенаправления на `https`.

У нас используется **passport-vkontakte**, который использует **passport-oauth2**, который в свою очередь имеет параметр `callbackUrl`. У нас он задается относительным путем. Т.к. между проксей Heroku и нашим приложением соединение по `http` и внутри некоторой сети, то нужно выставить этот параметр, чтобы **passport-oauth2** доверял http header от Heroku и выставлял protocol://host из заголовков перенаправленного запроса

2017-04-17 16:00 UTC, Gebon commented on configs/passport.js
> +passport.serializeUser((user, done) => {
Shorthand

2017-04-17 16:00 UTC, Gebon commented on configs/passport.js
> +passport.deserializeUser((id, done) => {
Shorthand

2017-04-17 16:00 UTC, Gebon commented on controllers/auth.js
> +        .then(() => {
Shorthand

2017-04-17 16:00 UTC, Gebon commented on controllers/auth.js
> +exports.logout = function (req, res) {
Arrow function

2017-04-17 16:00 UTC, Gebon commented on controllers/quests.js
>  exports.list = (req, res, next) => {
Shorthand

2017-04-17 16:00 UTC, Gebon commented on controllers/quests.js
>  exports.show = (req, res, next) => {
Shorthand

2017-04-17 16:00 UTC, Gebon commented on controllers/quests.js
>  exports.publish = (req, res, next) => {
Shorthand

2017-04-17 16:00 UTC, Gebon commented on package.json
> +    "crypto": "0.0.3",
Remove

2017-04-17 16:00 UTC, Gebon commented on utils/hbs-helpers.js
> +    return index < array.length ? array[index] : undefined;
index>0

2017-04-17 16:00 UTC, Gebon commented on utils/hbs-helpers.js
> + * {{questLink photo._id}}
Quest

2017-04-17 16:00 UTC, Gebon commented on views/blocks/quest_description/index.hbs
> +        {{#if this}}
Remove

2017-04-17 16:01 UTC, Gebon commented on configs/passport.js
> +passport.serializeUser((user, done) => {
Make ESLint rule

2017-04-17 16:18 UTC, LeMarck requested changes

2017-04-17 16:18 UTC, LeMarck commented on controllers/auth.js
> +    failureRedirect: '/login?failedStrategy=local'
[Почитай про **flash**](http://passportjs.org/docs/authenticate)

2017-04-17 16:18 UTC, LeMarck commented on package.json
> +    "crypto": "0.0.3",
Чем плох [*crypto*](https://nodejs.org/api/crypto.html)?

2017-04-17 16:18 UTC, LeMarck commented on views/pages/login/index.hbs
> +            <p></p>
Забавно. А давай всё переверстаем?

2017-04-17 17:19 UTC, Gebon commented on views/pages/login/index.hbs
> +            <p></p>
Давай, хорошее предложение. Прямо в твоем духе)

2017-04-17 17:20 UTC, Gebon commented on package.json
> +    "crypto": "0.0.3",
Тем, что оно есть в Node.js по умолчанию

2017-04-17 17:36 UTC, Gebon commented on package.json
> +    "crypto": "0.0.3",
А, ты видимо не видел мой коммент к этой же строке? Там написано remove

2017-04-17 17:38 UTC, Gebon commented on views/pages/login/index.hbs
> +            <p></p>
Если бы ты умел пользоваться блеймом, то увидел бы, что эта штука осталась еще от Сергея. Я ее, конечно, уберу и заменю на уже существующие. Но для начала ревью это не мешает

2017-04-17 17:52 UTC, LeMarck commented on package.json
> +    "crypto": "0.0.3",
Забавно. Он всем комментариям выставляет время окончания ревью.
Когда я писал про это. Твоего комментария ещё не было

2017-04-17 17:56 UTC, LeMarck commented on views/pages/login/index.hbs
> +            <p></p>
Просто ты как бы уже сделал не мало коммитов, но всё ещё продолжаешь тянуть за собой этот хвост

2017-04-17 18:02 UTC, Gebon commented on views/pages/login/index.hbs
> +            <p></p>
Ну ты мог бы нормально без сарказма/иронии. Или религия не позволяет?

2017-04-18 11:02 UTC, IrinaSed requested changes

2017-04-18 11:02 UTC, IrinaSed commented on auth/twitter-strategy.js
> +        .then(user => user ? done(null, user) : saveTwitterAccount(profile, done))
Тут не понимаю, зачем если !user сохранять аккаунт???

2017-04-18 11:47 UTC, Gebon commented on auth/twitter-strategy.js
> +        .then(user => user ? done(null, user) : saveTwitterAccount(profile, done))
Если пользователя с таким twitterId нет в базе, то значит его нужно сохранить там. Аналог регистрации

2017-04-18 15:07 UTC, IrinaSed commented on middlewares/error.js
> +    return (err, req, res) => {
верни next

2017-04-18 15:07 UTC, IrinaSed commented on routes/photo.js
>      app.get('/photos/:id', recaptcha.middleware.render, photos.show);
не работает

2017-04-18 15:07 UTC, IrinaSed approved these changes

2017-04-20 08:08 UTC, LeMarck approved these changes

2017-04-20 08:08 UTC, LeMarck commented on utils/hbs-helpers.js
> +function getArrayItem(array, index) {
`const getArrayItem = (array, index) => { }`

2017-04-20 08:08 UTC, LeMarck commented on utils/hbs-helpers.js
> +helpers.questLink = id => `/quests/${id}`;
Может сделаем такой вариант?
```javascript
helpers.link = (template, ...items) => {
    var op = items.pop();
    items.forEach((item, index) => {
        template = template.replace('%${index}', item);
    });
    return template;
};
```

2017-04-20 08:08 UTC, LeMarck commented on views/blocks/header/index.hbs
> +            <div class="header__user">
Я хотел пользователя под кнопку меню убрать.

2017-04-20 08:32 UTC, Gebon commented on utils/hbs-helpers.js
> +helpers.questLink = id => `/quests/${id}`;
Эти ссылки в будущем будут генерироваться в отдельном файле. Поэтому думаю, что пока и так сойдет. Смысл был именно в том, чтобы view не знали ничего про структуру ссылок, а получали их извне, если я правильно понял, что ты предлагаешь использовать это потом как `{{link '/quests/%0' id}}`
#87

2017-04-20 08:33 UTC, Gebon commented on views/blocks/header/index.hbs
> +            <div class="header__user">
Это, я думаю, в отдельной задаче для фронта сделаем?

2017-04-20 08:38 UTC, LeMarck commented on views/blocks/header/index.hbs
> +            <div class="header__user">
Это было пояснение, почему `header__details` был спрятан за `if`

2017-04-20 08:57 UTC, Gebon commented on views/blocks/header/index.hbs
> +            <div class="header__user">
Понял тебя, но это было все-таки неверное решение. Если так сделать, то на мобилах никогда не покажутся кнопки войти/зарегистрироваться. А вот сейчас как раз так, как ты хотел

2017-04-20 09:09 UTC, LeMarck commented on views/blocks/header/index.hbs
> +            <div class="header__user">
В том то и дело, что было следующий: если есть `_user`, то `if` становится `true` и ничего не показывает, а иначе показывается блок `else` в котором есть кат для мобилок

2017-04-20 09:11 UTC, LeMarck commented on views/blocks/header/index.hbs
> +            <div class="header__user">
`_user` принимает аргументом `req.locale.user`, который зависит от результата passport.js который добавляет или нет поле user в req

2017-04-20 09:17 UTC, Gebon commented on views/blocks/header/index.hbs
> +            <div class="header__user">
А да, сам затупил. Ок, тогда возвращаю

2017-04-20 09:20 UTC, Gebon commented on views/blocks/header/index.hbs
> +            <div class="header__user">
Кек, это даже не я менял :D Я еще думаю, почему это я не помню ничего про это

2017-04-20 09:28 UTC, merged